Repository verdaccio/verdaccio, pull requests merged in 2018-11, with the labels that each got.

#1084 chore: update readme
  README.md
  assets/sponsor/crowdin/logo.png
  assets/sponsor/jetbrains/logo.png
Labels: code-review

#1103 Fixed commit lint
  package.json
  yarn.lock
Labels: bug

#1115 chore: trans update mapping
  crowdin.yaml
  website/languages.js
Labels: code-review, internal

#1116 chore: enable Italian and French on website
  website/languages.js
Labels: translations

#1109 bug #1105: answer 401 in case no credentials were sent.
  src/lib/auth-utils.js
  src/lib/utils.js
  test/unit/api/api.spec.js
Labels: bug

#1114 refactor: submit login form on enter press
  src/webui/components/Login/index.js
  test/unit/webui/components/__snapshots__/login.spec.js.snap
Labels: in progress

#1118 Refactor <Help /> component
  package.json
  src/webui/components/CopyToClipBoard/styles.js
  src/webui/components/Help/help.scss
  src/webui/components/Help/index.js
  src/webui/components/Help/styles.js
  test/e2e/e2e.spec.js
  test/unit/webui/components/__snapshots__/copyToClipBoard.spec.js.snap
  test/unit/webui/components/__snapshots__/help.spec.js.snap
  test/unit/webui/components/__snapshots__/packagelist.spec.js.snap
  test/unit/webui/components/help.spec.js
  test/unit/webui/components/packagelist.spec.js
  yarn.lock
Labels: in progress

#1123 ci: use CircleCI workspaces to share data among steps
  .circleci/config.yml
Labels: ci-build

#1124 refactor: removes unused getFilteredPackage method
  src/webui/app.js
Labels: in progress

#1068 feat: endpoints change password on ui
  src/api/web/endpoint/user.js
  src/lib/constants.js
  test/unit/api/api.spec.js
  test/unit/api/api.web.spec.js
  test/unit/api/mock.js
  test/unit/partials/config-unit-mock-server-test.yaml
  test/unit/partials/config/yaml/api.spec/web-config.yaml
Labels: code-review

#1126 feat: stop hit proxies on search web UI
  src/api/endpoint/api/dist-tags.js
  src/api/endpoint/api/package.js
  src/api/web/endpoint/package.js
  src/api/web/endpoint/search.js
  src/lib/storage.js
  types/index.js
Labels: code-review

#1128 refactor: <Search /> component
  src/webui/app.js
  src/webui/components/AutoComplete/index.js
  src/webui/components/AutoComplete/types.js
  src/webui/components/Header/index.js
  src/webui/components/Header/styles.js
  src/webui/components/Header/types.js
  src/webui/components/PackageList/index.js
  src/webui/components/Search/index.js
  src/webui/components/Search/types.js
  src/webui/pages/home/index.js
  src/webui/router.js
  src/webui/utils/api.js
Labels: in progress, refactor

#1125 refactor: Footer
  package.json
  src/webui/components/Footer/earth.svg
  src/webui/components/Footer/flags/brazil-1f1e7-1f1f7.svg
  src/webui/components/Footer/flags/china-1f1e8-1f1f3.svg
  src/webui/components/Footer/flags/india-1f1ee-1f1f3.svg
  src/webui/components/Footer/flags/nicaragua-1f1f3-1f1ee.svg
  src/webui/components/Footer/flags/pakistan-1f1f5-1f1f0.svg
  src/webui/components/Footer/flags/spain-1f1ea-1f1f8.svg
  src/webui/components/Footer/footer.scss
  src/webui/components/Footer/index.js
  src/webui/components/Footer/logo.svg
  src/webui/components/Footer/styles.js
  src/webui/components/Icon/img/austria.svg
  src/webui/components/Icon/img/brazil.svg
  src/webui/components/Icon/img/china.svg
  src/webui/components/Icon/img/earth.svg
  src/webui/components/Icon/img/india.svg
  src/webui/components/Icon/img/nicaragua.svg
  src/webui/components/Icon/img/pakistan.svg
  src/webui/components/Icon/img/spain.svg
  src/webui/components/Icon/img/verdaccio.svg
  src/webui/components/Icon/index.js
  src/webui/components/Icon/styles.js
  src/webui/components/Icon/types.js
  src/webui/components/Link/types.js
  src/webui/components/Logo/img/logo.svg
  src/webui/utils/styles/media.js
  test/unit/partials/mock-store/jquery/package.json.tmp06759389759177314
  test/unit/webui/components/__snapshots__/footer.spec.js.snap
  test/unit/webui/components/__snapshots__/header.spec.js.snap
  test/unit/webui/components/footer.spec.js
  tools/webpack.config.js
  yarn.lock
Labels: Web, in progress, refactor
