Repository verdaccio/verdaccio, pull requests merged in 2018-07, with the labels that each got.

#800 refactor: config and utils
  .eslintrc
  Dockerfile
  flow-typed/npm/jest_v23.x.x.js
  jest.config.js
  package.json
  src/api/index.js
  src/lib/auth-utils.js
  src/lib/auth.js
  src/lib/bootstrap.js
  src/lib/config-utils.js
  src/lib/config.js
  src/lib/constants.js
  src/lib/storage-utils.js
  src/lib/storage.js
  src/lib/up-storage.js
  src/lib/utils.js
  test/integration/config_nocache.yaml
  test/unit/api/api.pkg.access.spec.js
  test/unit/api/api.spec.js
  test/unit/api/config-utils.spec.js
  test/unit/api/config.spec.js
  test/unit/api/search.spec.js
  test/unit/api/up-storage.spec.js
  test/unit/partials/config/config_access.js
  test/unit/partials/config/yaml/deprecated-pkgs-basic.yaml
  test/unit/partials/config/yaml/pkgs-basic.yaml
  test/unit/partials/config/yaml/pkgs-custom.yaml
  test/unit/partials/config/yaml/pkgs-empty.yaml
  test/unit/partials/config/yaml/pkgs-multi-group.yaml
  test/unit/partials/config/yaml/pkgs-nosuper-wildcard-custom.yaml
  test/unit/partials/config/yaml/uplink-basic.yaml
  test/unit/partials/config/yaml/uplink-wrong.yaml
  types/index.js
  yarn.lock
Labels: code-review

#815 refactor: flow 0.7x.0
  .babelrc
  flow-typed/npm/express_v4.16.x.js
  package.json
  src/api/index.js
  src/lib/auth-utils.js
  src/lib/auth.js
  src/lib/constants.js
  src/lib/local-storage.js
  src/lib/plugin-loader.js
  src/lib/storage.js
  src/lib/up-storage.js
  src/lib/utils.js
  test/flow/plugins/auth/example.auth.plugin.js
  test/flow/plugins/middleware/example.middleware.plugin.js
  test/flow/plugins/partials/config.example.js
  test/flow/plugins/storage/example.storage.plugin.js
  test/unit/api/plugin_loader.spec.js
  test/unit/partials/plugin/authenticate.js
  types/index.js
  yarn.lock
Labels: code-review

#822 feat: Added support for external plugin directory
  Dockerfile
  conf/default.yaml
  conf/docker.yaml
  conf/full.yaml
  docs/config.md
  docs/docker.md
  package.json
  src/lib/config.js
  src/lib/plugin-loader.js
  types/index.js
  yarn.lock
Labels: Docker, Feature Request, plugins

#833 refactor: package and package sidebar code refactoring
  jest.config.js
  src/webui/.eslintrc
  src/webui/components/Footer/index.js
  src/webui/components/Package/index.js
  src/webui/components/PackageDetail/index.js
  src/webui/components/PackageList/index.js
  src/webui/components/PackageSidebar/index.jsx
  src/webui/components/PackageSidebar/modules/Dependencies/index.jsx
  src/webui/components/PackageSidebar/modules/Infos/index.jsx
  src/webui/components/PackageSidebar/modules/LastSync/index.jsx
  src/webui/components/PackageSidebar/modules/Maintainers/index.jsx
  src/webui/modules/detail/index.jsx
  src/webui/utils/DateUtils.js
  src/webui/utils/package.js
  test/unit/empty.js
  test/unit/setup.js
  test/unit/webui/components/PackageSidebar/__snapshots__/dependencies.spec.js.snap
  test/unit/webui/components/PackageSidebar/__snapshots__/infos.spec.js.snap
  test/unit/webui/components/PackageSidebar/__snapshots__/lastsync.spec.js.snap
  test/unit/webui/components/PackageSidebar/__snapshots__/maintainers.spec.js.snap
  test/unit/webui/components/PackageSidebar/dependencies.spec.js
  test/unit/webui/components/PackageSidebar/infos.spec.js
  test/unit/webui/components/PackageSidebar/lastsync.spec.js
  test/unit/webui/components/PackageSidebar/maintainers.spec.js
  test/unit/webui/components/__snapshots__/footer.spec.js.snap
  test/unit/webui/components/__snapshots__/package.spec.js.snap
  test/unit/webui/components/__snapshots__/packagelist.spec.js.snap
  test/unit/webui/components/footer.spec.js
  test/unit/webui/components/package.spec.js
  test/unit/webui/components/packagedetail.spec.js
  test/unit/webui/components/store/packageMeta.js
  test/unit/webui/utils/package.spec.js
  tools/dev.server.js
Labels: code-review

#854 fix: Authentication Plugins / plugin[method] is not a function (add_user method)
  src/lib/auth.js
Labels: High Priority, bug

#852 chore: add bundlesize integration
  .circleci/config.yml
  package.json
  yarn.lock
Labels: Feature Request
