Repository verdaccio/verdaccio, pull requests merged in 2018-06, with the labels that each got.

#736 feat: add published date and license on ui
  src/lib/storage.js
  src/webui/src/components/Package/index.js
  src/webui/src/components/Package/package.scss
  src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx
  src/webui/src/components/PackageSidebar/modules/Maintainers/index.jsx
  src/webui/src/styles/variable.scss
  src/webui/src/utils/DateUtils.js
  test/webui/components/__snapshots__/package.spec.js.snap
  test/webui/components/__snapshots__/packagelist.spec.js.snap
  test/webui/components/package.spec.js
Labels: Web, code-review

#734 refactor: crypto utils
  src/api/endpoint/api/user.js
  src/api/middleware.js
  src/lib/auth.js
  src/lib/config.js
  src/lib/crypto-utils.js
  src/lib/local-storage.js
  src/lib/storage-utils.js
  src/utils/string.js
  src/utils/user.js
  types/index.js
Labels: code-review

#748 feat: added information about package publisher for notifications
  docs/notifications.md
  src/api/endpoint/api/publish.js
  src/lib/notify.js
  test/functional/notifications/notify.js
Labels: Feature Request

#759 fix: normalize package was broken #758
  src/lib/storage-utils.js
  test/unit/storage-utils.spec.js
Labels: High Priority

#769 fix: dynamic date generation for <Package /> component test
  test/webui/components/__snapshots__/package.spec.js.snap
  test/webui/components/package.spec.js
Labels: code-review

#764 feat: adds support for ascii doc preview in readme
  flow-typed/npm/asciidoctor.js_vx.x.x.js
  package.json
  src/api/web/endpoint/package.js
  src/lib/utils.js
  test/unit/utils.spec.js
  yarn.lock
Labels: code-review

#787 refactor: unit test
  conf/default.yaml
  conf/docker.yaml
  conf/full.yaml
  flow-typed/npm/axios_v0.17.x.js
  jest.config.unit.js
  src/api/endpoint/api/dist-tags.js
  src/api/index.js
  src/api/web/index.js
  src/lib/auth.js
  src/lib/bootstrap.js
  src/lib/constants.js
  src/lib/local-storage.js
  src/lib/up-storage.js
  src/lib/utils.js
  test/functional/config.functional.js
  test/functional/lib/environment.js
  test/functional/store/config-1.yaml
  test/functional/store/config-2.yaml
  test/functional/store/config-3.yaml
  test/jest.config.e2e.js
  test/jest.config.functional.js
  test/lib/server_process.js
  test/test.conf.js
  test/unit/api/api.spec.js
  test/unit/api/basic_system.spec.js
  test/unit/api/cli.spec.js
  test/unit/api/config.spec.js
  test/unit/api/listen_addr.spec.js
  test/unit/api/mock.js
  test/unit/api/store.spec.js
  test/unit/api/up-storage.spec.js
  test/unit/functionalLibs/request.spec.js
  test/unit/partials/config-unit-test.yaml
  test/unit/partials/config/access.js
  test/unit/partials/config/index.js
  test/unit/partials/mock-store/.sinopia-db.json
  test/unit/partials/mock-store/corrupted-package/package.json
  test/unit/partials/mock-store/jquery/jquery-1.5.1.tgz
  test/unit/partials/mock-store/jquery/package.json
  test/unit/partials/mock-store/vue/package.json
  test/unit/webui/components/packagedetail.spec.js
Labels: code-review

#793 chore(ci): improve the workflow publishing doc only when releasing
  .circleci/config.yml
Labels: ci-build
