Repository verdaccio/verdaccio, pull requests merged in 2018-10, with the labels that each got.

#1035 Add space in curly braces -> object-curly-spacing
  .prettierrc
  package.json
  src/api/debug/index.js
  src/api/endpoint/api/dist-tags.js
  src/api/endpoint/api/package.js
  src/api/endpoint/api/ping.js
  src/api/endpoint/api/publish.js
  src/api/endpoint/api/search.js
  src/api/endpoint/api/user.js
  src/api/endpoint/api/whoami.js
  src/api/endpoint/index.js
  src/api/index.js
  src/api/middleware.js
  src/api/web/api.js
  src/api/web/endpoint/package.js
  src/api/web/endpoint/search.js
  src/api/web/endpoint/user.js
  src/api/web/index.js
  src/config/env.js
  src/lib/auth-utils.js
  src/lib/auth.js
  src/lib/bootstrap.js
  src/lib/cli/utils.js
  src/lib/config-path.js
  src/lib/config-utils.js
  src/lib/config.js
  src/lib/crypto-utils.js
  src/lib/local-storage.js
  src/lib/logger.js
  src/lib/metadata-utils.js
  src/lib/notify/index.js
  src/lib/notify/notify-request.js
  src/lib/plugin-loader.js
  src/lib/search.js
  src/lib/storage-utils.js
  src/lib/storage.js
  src/lib/up-storage.js
  src/lib/update-banner.js
  src/lib/uplink-util.js
  src/lib/utils.js
  src/webui/components/CopyToClipBoard/index.js
  src/webui/components/Header/index.js
  src/webui/components/Header/interfaces.js
  src/webui/components/Header/styles.js
  src/webui/components/Link/index.js
  src/webui/components/Link/interfaces.js
  src/webui/components/RegistryInfoDialog/index.js
  src/webui/components/RegistryInfoDialog/interfaces.js
  src/webui/components/RegistryInfoDialog/styles.js
  test/e2e/e2e.spec.js
  test/unit/setup.js
  test/unit/webui/components/copyToClipBoard.spec.js
  test/unit/webui/components/header.spec.js
  test/unit/webui/components/login.spec.js
Labels: High Priority

#1030 refactor: typo fixes
  src/api/endpoint/api/dist-tags.js
  src/api/endpoint/api/package.js
  src/api/endpoint/api/publish.js
  src/api/index.js
  src/api/web/endpoint/package.js
  src/api/web/endpoint/search.js
  src/lib/cli.js
  src/lib/config-path.js
  src/lib/config-utils.js
  src/lib/config.js
  src/lib/constants.js
  src/lib/crypto-utils.js
  src/lib/local-storage.js
  src/lib/logger.js
  src/lib/metadata-utils.js
  src/lib/plugin-loader.js
  src/lib/search.js
  src/lib/status-cats.js
  src/lib/storage-utils.js
  src/lib/storage.js
  src/lib/up-storage.js
  src/lib/utils.js
  test/functional/basic/basic.js
  test/functional/package/scoped.js
  test/functional/sanity/nullstorage.js
  test/functional/tags/dist-tags-merge.js
  test/unit/api/api.spec.js
  test/unit/api/local-storage.spec.js
  test/unit/api/plugin_loader.spec.js
  test/unit/api/storage-utils.spec.js
  test/unit/api/utils.spec.js
Labels: code-review

#1037 Centralize Loading
  src/webui/components/Footer/footer.scss
  src/webui/components/Spinner/index.js
  src/webui/components/Spinner/interfaces.js
  src/webui/components/Spinner/styles.js
  src/webui/modules/detail/detail.scss
  src/webui/modules/detail/index.jsx
  src/webui/modules/home/index.js
  src/webui/router.js
  src/webui/styles/global.scss
Labels: Web, refactor

#1040 Get rid off require('../lib/logger')
  src/api/index.js
  src/api/middleware.js
  src/lib/storage.js
Labels: hacktoberfest

#1041 refactor: restructure Utils import
  src/api/web/index.js
  src/lib/cli.js
  src/lib/logger.js
Labels: hacktoberfest

#1042 refactor: Awshanks/assertfixes
  test/functional/tags/tags.js
Labels: hacktoberfest

#1039 refactor: tests for notify request service
  src/lib/notify/notify-request.js
  test/unit/api/notify-request.spec.js
Labels: code-review, hacktoberfest

#1043 refactor: remove usage of assert from cache.js [#973]
  test/functional/uplinks/cache.js
  test/unit/api/no_proxy.spec.js
Labels: hacktoberfest

#1050 refactor: replace all 404 with NOT_FOUND constant
  src/api/web/endpoint/package.js
  src/lib/local-storage.js
  test/functional/tags/tags.js
  test/unit/api/api.pkg.access.spec.js
  test/unit/api/local-storage.spec.js
  test/unit/api/up-storage.spec.js
  test/unit/functionalLibs/request.spec.js
Labels: hacktoberfest

#1051 refactor: remove unnecessary FlowFixMe
  src/api/endpoint/api/publish.js
  src/api/web/api.js
  src/lib/local-storage.js
  src/lib/storage-utils.js
  src/lib/storage.js
  src/lib/up-storage.js
  test/unit/api/config-utils.spec.js
Labels: hacktoberfest

#1054 test: add scenarios where publish or access are missing
  test/unit/api/config-utils.spec.js
  test/unit/partials/config/yaml/pkgs-basic-no-access.yaml
  test/unit/partials/config/yaml/pkgs-basic-no-proxy.yaml
  test/unit/partials/config/yaml/pkgs-basic-no-publish.yaml
Labels: High Priority, refactor

#1027 Added user's greetings
  src/webui/app.js
  src/webui/components/Header/index.js
  src/webui/components/Header/styles.js
  src/webui/components/Label/index.js
  src/webui/components/Label/interfaces.js
  src/webui/utils/styles/ellipsis.js
  src/webui/utils/styles/spacings.js
  test/e2e/e2e.spec.js
Labels: Web, code-review

#1034 feat: add support for profile cli command #392 (change password)
  .gitignore
  package.json
  src/api/endpoint/api/user.js
  src/api/endpoint/api/v1/profile.js
  src/api/endpoint/index.js
  src/lib/auth-utils.js
  src/lib/auth.js
  src/lib/constants.js
  test/flow/plugins/auth/example.auth.plugin.js
  test/unit/api/__api-helper.js
  test/unit/api/api.profile.spec.js
  test/unit/api/api.spec.js
  test/unit/partials/config/yaml/profile/profile.yaml
  types/index.js
  yarn.lock
Labels: High Priority, new commands

#1073 fix: click on logo break ui
  src/webui/components/Header/index.js
  test/unit/webui/components/__snapshots__/header.spec.js.snap
Labels: High Priority, bug

#1056 test: Increase coverage publish api tests
  src/api/endpoint/api/publish.js
  src/api/index.js
  src/lib/utils.js
  test/unit/api/__snapshots__/api.publish.spec.js.snap
  test/unit/api/api.publish.spec.js
  test/unit/api/notify-request.spec.js
Labels: code-review

#1099 Refactored 'ReadMe' -> Added flow
  flow-typed/npm/github-markdown-css_vx.x.x.js
  src/webui/components/PackageDetail/index.js
  src/webui/components/Readme/index.js
  src/webui/components/Readme/readme.scss
  src/webui/components/Readme/types.js
  test/e2e/e2e.spec.js
  test/unit/webui/components/__snapshots__/readme.spec.js.snap
  test/unit/webui/components/readme.spec.js
Labels: Web, flow, in progress

#1100 Refactored 'NoItems' -> Added flow and css in js
  src/webui/components/NoItems/index.js
  src/webui/components/NoItems/noItems.scss
  src/webui/components/NoItems/styles.js
  src/webui/components/NoItems/types.js
  test/unit/webui/components/__snapshots__/noitems.spec.js.snap
  test/unit/webui/components/noitems.spec.js
Labels: Web, flow, in progress

#1098 Refactored 'NotFound' -> Added flow and css in js
  src/webui/components/NotFound/404.scss
  src/webui/components/NotFound/index.js
  src/webui/components/NotFound/styles.js
  src/webui/components/NotFound/types.js
  src/webui/pages/detail/index.jsx
  test/unit/webui/components/__snapshots__/notfound.spec.js.snap
  test/unit/webui/components/notfound.spec.js
Labels: Web, flow, in progress
