Repository verdaccio/verdaccio, pull requests merged in 2019-02, with the labels that each got.

#1206 feat: use verdaccio babel preset + beta deps
  .babelrc
  package.json
  src/lib/constants.js
  src/lib/local-storage.js
  test/functional/package/access.js
  test/functional/sanity/nullstorage.js
  test/functional/store/config-1.yaml
  test/unit/webui/components/__snapshots__/packagelist.spec.js.snap
  yarn.lock
Labels: Feature Request, stack

#1227 Feat auth jwt plugin
  src/lib/auth.js
Labels: Feature Request, discuss, plugins

#1223 feat: ability to restrict unpublish action to certain users #492
  .circleci/config.yml
  .gitignore
  conf/default.yaml
  conf/docker.yaml
  package.json
  src/api/endpoint/api/publish.js
  src/api/index.js
  src/lib/auth-utils.js
  src/lib/auth.js
  src/lib/config-utils.js
  test/functional/tags/tags.js
  test/unit/api/__snapshots__/api.publish.spec.js.snap
  test/unit/api/__snapshots__/update-banner.spec.js.snap
  test/unit/api/api.jwt.spec.js
  test/unit/api/api.pkg.access.spec.js
  test/unit/api/api.profile.spec.js
  test/unit/api/api.spec.js
  test/unit/api/api.web.spec.js
  test/unit/api/auth-utils.spec.js
  test/unit/api/auth.spec.js
  test/unit/api/basic_system.spec.js
  test/unit/api/cli.spec.js
  test/unit/api/local-storage.spec.js
  test/unit/api/search.spec.js
  test/unit/api/store.spec.js
  test/unit/api/up-storage.spec.js
  test/unit/partials/config/index.js
  test/unit/partials/config/plugin.js
  test/unit/partials/config/yaml/api.spec.yaml
  test/unit/partials/config/yaml/api.web.spec.yaml
  test/unit/partials/config/yaml/default.yaml
  test/unit/partials/config/yaml/store.spec.yaml
  test/unit/webui/components/__snapshots__/notfound.spec.js.snap
  yarn.lock
Labels: Feature Request, auth

#1240 fix: overrides existing package to zero bytes file #1191
  package.json
  src/lib/local-storage.js
  test/unit/api/local-storage.spec.js
  yarn.lock
Labels: High Priority
