Repository verdaccio/verdaccio, pull requests merged in 2019-07, with the labels that each got.

#1360 feat: storage plugins can throw http status codes
  package.json
  src/lib/local-storage.ts
  src/lib/utils.ts
  yarn.lock
Labels: topic: feature request

#1373 feat: prevent secrets from leaking to source control
  .secrets-baseline
  package.json
  yarn.lock
Labels: Docker, security, topic: feature request

#1417 chore: minor refactor to eliminate code redundancy
  src/lib/utils.ts
Labels: dev: code-review, dev: refactor
