Repository verdaccio/verdaccio, pull requests merged in 2019-06, with the labels that each got.

#1342 fix: update security policy details
  SECURITY.md
Labels: security

#1347 fix: force authenticate on login
  src/api/endpoint/api/user.js
  test/unit/api/__api-helper.js
  test/unit/api/api.jwt.spec.js
Labels: dev: high priority

#1343 chore: add testing development notes
  jest.config.js
  test/README.md
  test/unit/api/__api-helper.js
  test/unit/api/api.__test.template.spec.js
  test/unit/api/api.jwt.spec.js
  test/unit/empty.js
Labels: dev: high priority

#1331 Return 503 to npm/yarn on uplink connection timeout
  package.json
  src/lib/storage.js
  test/functional/fixtures/plugins/middlewares.uplink.js
  test/functional/index.spec.js
  test/functional/store/config-1.yaml
  test/functional/store/config-3.yaml
  test/functional/uplinks/timeout.js
  yarn.lock
Labels: bug: fixed, dev: discuss
