Repository verdaccio/verdaccio, pull requests merged in 2019-05, with the labels that each got.

#1161 Filter packages
  package.json
  src/api/index.js
  src/lib/storage.js
  test/unit/api/api.spec.js
  test/unit/partials/mock-store/npm_test/package.json
  test/unit/partials/plugin/filter.js
Labels: dev: code-review, dev: required documentation, dev: required examples, dev: unit test required

#1311 feat: update readme v3
  package.json
  src/api/endpoint/api/publish.js
  src/api/middleware.js
  src/api/web/endpoint/package.js
  src/lib/utils.js
  src/webui/components/PackageSidebar/modules/Infos/index.jsx
  src/webui/components/Readme/index.js
  src/webui/utils/url.js
  test/functional/readme/readme.js
  test/unit/api/__snapshots__/utils.spec.js.snap
  test/unit/api/api.spec.js
  test/unit/api/utils.spec.js
  yarn.lock
Labels: dev: high priority

#1312 feat: update readme v4
  package.json
  src/lib/utils.js
  test/functional/readme/readme.js
  test/unit/api/__snapshots__/utils.spec.js.snap
  test/unit/api/utils.spec.js
  test/unit/partials/config-unit-mock-server-test.yaml
  yarn.lock
Labels: dev: high priority

#1258 feat: parse YAML/JSON/JS config file
  src/lib/utils.js
  test/unit/modules/config/config.spec.js
  test/unit/modules/utils/config-utils.spec.js
  test/unit/partials/config/js/default.js
  test/unit/partials/config/js/invalid.js
  test/unit/partials/config/json/default.json
  test/unit/partials/config/json/invalid.json
Labels: dev: code-review, topic: feature request

#1307 feat: prepare release v4
  README.md
  conf/full.yaml
  scripts/publish.sh
Labels: topic: feature request
