Repository verdaccio/verdaccio, pull requests merged in 2019-10, with the labels that each got.

#1498 [Docs]: minor tweak
  README.md
Labels: hacktoberfest 🎃

#1499 chore: remove jwt from default config
  conf/default.yaml
Labels: dev: high priority, hacktoberfest 🎃

#1500 chore: remove jwt from docker config
  conf/docker.yaml
Labels: dev: high priority, hacktoberfest 🎃, security

#1492 ci(github): migrate release workflow from old syntax
  .github/main.workflow
  .github/workflows/release.yml
Labels: dev: ci-build, hacktoberfest 🎃

#1493 ci(github): migrate docker-publish-pre-check from old syntax
  .github/workflows/docker-publish-pre-check.yml
Labels: dev: ci-build, hacktoberfest 🎃

#1494 ci(github): add a CI workflow using Github Actions
  .github/workflows/ci.yml
Labels: dev: ci-build, hacktoberfest 🎃

#1495 ci(circleci): remove deprecated versions, improve names and coverage
  .circleci/config.yml
Labels: dev: ci-build, hacktoberfest 🎃

#1496 ci(circleci): use CircleCI 2.1 syntax improvements
  .circleci/config.yml
Labels: dev: ci-build, hacktoberfest 🎃

#1505 fix: comment out experiments from configuration files
  conf/default.yaml
  conf/docker.yaml
  test/unit/modules/config/config.spec.ts
Labels: issue: bug

#1506 fix: allow add to request agentOptions
  src/lib/up-storage.ts
Labels: bug: fixed, hacktoberfest 🎃

#1497 ci(circleci): store test results in junit format
  .circleci/config.yml
  .gitignore
  jest.config.js
  package.json
  yarn.lock
Labels: dev: ci-build, hacktoberfest 🎃

#1512 fix: minor typos, formatting, and docs
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  conf/README.md
  wiki/README.md
Labels: hacktoberfest 🎃

#1513 chore: minor tweak
  src/api/endpoint/api/publish.ts
Labels: hacktoberfest 🎃

#1524 chore: removes 3x unnecessary @ts-ignore comments
  src/lib/logger.ts
Labels: hacktoberfest 🎃

#1532 fix: security vulnerability at readme in dompurify dep
  package.json
  yarn.lock
Labels: hacktoberfest 🎃

#1507 chore: update typescript@3.7.0-beta (PoC)
  package.json
  yarn.lock
Labels: hacktoberfest 🎃
