Repository verdaccio/verdaccio, pull requests merged in 2019-12, with the labels that each got.

#1596 refactor: minor code refactoring
  src/lib/utils.ts
Labels: dev: refactor

#1612 refactor: simplify the conditional expression
  src/api/endpoint/api/stars.ts
Labels: dev: code-review

#1598 fix: search api will not set magic date header when requesting /-/all without ?since
  src/api/endpoint/api/search.ts
Labels: dev: code-review

#1623 feat: update @verdaccio/ui-theme@0.3.9
  package.json
  test/e2e/e2e.spec.js
  yarn.lock
Labels: bug: fixed, topic: web
