Repository verdaccio/verdaccio, pull requests merged in 2019-08, with the labels that each got.

#1418 fix(chore): remove stub type definition for handlebars
  package.json
  yarn.lock
Labels: dependencies, dev: code-review

#1438 fix: mkdir failed and ec2 infinitely re-launch
  contrib/aws/cloudformation-ec2-efs.yaml
Labels: dev: code-review

#1444 Lint the lockfile for security policies
  .secrets-baseline
  package.json
  yarn.lock
Labels: dev: code-review, security
