Repository verdaccio/verdaccio, pull requests merged in 2020-12, with the labels that each got.

#2012 fix: doubled request logs in node.js >= 11
  src/api/middleware.ts
Labels: bug: fixed, issue: bug

#2013 feat(experiment): set bytesin log as optional …
  conf/default.yaml
  src/api/index.ts
  src/api/middleware.ts
Labels: topic: feature request

#2014 feat: enable keep alive on configuration by default
  conf/default.yaml
  conf/docker.yaml
Labels: performance

#2026 feat: update @verdaccio/ui-theme
  package.json
  test/unit/modules/api/api.spec.ts
  test/unit/modules/uplinks/headers.auth.spec.ts
  yarn.lock
Labels: topic: feature request

#2027 feat: skip log static content from web
  src/api/middleware.ts
Labels: topic: feature request

#2031 publishing multi-arch image
  .github/workflows/docker-publish.yml
  Dockerfile
Labels: Docker, dev: discuss
