Repository verdaccio/verdaccio, pull requests merged in 2020-10, with the labels that each got.

#1953 feat: improve legacy token signature by removing deprecated crypto.cr…
  .changeset/gentle-trains-switch.md
  docs/env.variables.md
  package.json
  packages/api/src/user.ts
  packages/api/src/v1/token.ts
  packages/api/src/whoami.ts
  packages/auth/package.json
  packages/auth/src/auth.ts
  packages/auth/src/crypto-utils.ts
  packages/auth/src/index.ts
  packages/auth/src/jwt-token.ts
  packages/auth/src/legacy-token.ts
  packages/auth/src/token.ts
  packages/auth/src/utils.ts
  packages/auth/test/auth-utils.spec.ts
  packages/auth/test/crypto-utils.spec.ts
  packages/auth/test/legacy-token.spec.ts
  packages/commons/src/constants.ts
  packages/config/package.json
  packages/config/src/config.ts
  packages/config/src/index.ts
  packages/config/src/token.ts
  packages/config/test/token.spec.ts
  packages/core/types/index.d.ts
  packages/mock/package.json
  packages/mock/src/mock-api.ts
  packages/mock/src/request.ts
  packages/mock/src/server.ts
  packages/node-api/package.json
  packages/server/src/server.ts
  packages/server/test/api/index.spec.ts
  packages/store/test/local-storage.spec.ts
  packages/types/src/index.ts
  packages/utils/src/utils.ts
  packages/verdaccio/package.json
  packages/verdaccio/test/functional/adduser/adduser.js
  packages/verdaccio/test/functional/package/access.ts
  packages/verdaccio/test/functional/package/gzip.ts
  packages/verdaccio/test/types-test/plugins/middleware/example.middleware.plugin.ts
  packages/verdaccio/tsconfig.json
  pnpm-lock.yaml
Labels: topic: feature request

#1962 feat: migrate 4.x yarn 1 to yarn 2
  .babelrc
  .circleci/config.yml
  .dockerignore
  .github/workflows/ci.yml
  .github/workflows/e2e-angular-cli-workflow.yml
  .github/workflows/e2e-gatsbyjs-cli-workflow.yml
  .github/workflows/e2e-jest-workflow.yml
  .github/workflows/release.yml
  .gitignore
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-berry.cjs
  .yarnrc
  .yarnrc.yml
  Dockerfile
  babel.config.js
  package.json
  src/api/web/endpoint/package.ts
  test/e2e-cli/setup/setup.ts
  test/e2e-cli/test/core/info.spec.ts
  yarn.lock
Labels: hacktoberfest 🎃, hacktoberfest-accepted

#1972 Improving typescript practices in `packages/web/src/endpoint/package.ts`
  .changeset/fifty-jars-rest.md
  packages/middleware/src/middleware.ts
  packages/web/src/endpoint/package.ts
Labels: hacktoberfest-accepted

#1975 refactor: relocate verdaccio-auth-memory plugin
  packages/plugins/auth-memory/.babelrc
  packages/plugins/auth-memory/CHANGELOG.md
  packages/plugins/auth-memory/LICENSE
  packages/plugins/auth-memory/README.md
  packages/plugins/auth-memory/jest.config.js
  packages/plugins/auth-memory/package.json
  packages/plugins/auth-memory/src/Memory.ts
  packages/plugins/auth-memory/src/index.ts
  packages/plugins/auth-memory/src/types/index.ts
  packages/plugins/auth-memory/test/index.spec.ts
  packages/plugins/auth-memory/tsconfig.build.json
  packages/plugins/auth-memory/tsconfig.json
  packages/plugins/memory/CHANGELOG.md
  packages/plugins/memory/LICENSE
  packages/plugins/memory/README.md
  pnpm-lock.yaml
Labels: hacktoberfest-accepted

#1976 refactor: relocate verdaccio-audit plugin
  packages/plugins/audit/.babelrc
  packages/plugins/audit/CHANGELOG.md
  packages/plugins/audit/LICENSE
  packages/plugins/audit/README.md
  packages/plugins/audit/jest.config.js
  packages/plugins/audit/package.json
  packages/plugins/audit/src/audit.ts
  packages/plugins/audit/src/index.ts
  packages/plugins/audit/src/types.ts
  packages/plugins/audit/tests/audit.spec.ts
  packages/plugins/audit/tsconfig.build.json
  packages/plugins/audit/tsconfig.json
  pnpm-lock.yaml
Labels: hacktoberfest-accepted

#1977 refactor: relocate verdaccio-aws-storage plugin
  packages/plugins/aws-storage/.babelrc
  packages/plugins/aws-storage/.eslintrc
  packages/plugins/aws-storage/CHANGELOG.md
  packages/plugins/aws-storage/LICENSE
  packages/plugins/aws-storage/README.md
  packages/plugins/aws-storage/jest.config.js
  packages/plugins/aws-storage/package.json
  packages/plugins/aws-storage/src/addTrailingSlash.ts
  packages/plugins/aws-storage/src/config.ts
  packages/plugins/aws-storage/src/deleteKeyPrefix.ts
  packages/plugins/aws-storage/src/index.ts
  packages/plugins/aws-storage/src/s3Errors.ts
  packages/plugins/aws-storage/src/s3PackageManager.ts
  packages/plugins/aws-storage/src/setConfigValue.ts
  packages/plugins/aws-storage/tests/__fixtures__/pkg.ts
  packages/plugins/aws-storage/tests/__fixtures__/readme-test-corrupt/corrupt.js
  packages/plugins/aws-storage/tests/__fixtures__/readme-test/package.json
  packages/plugins/aws-storage/tests/__mocks__/Config.ts
  packages/plugins/aws-storage/tests/__mocks__/Logger.ts
  packages/plugins/aws-storage/tests/index.test.ts
  packages/plugins/aws-storage/tests/s3PackageManager.test.ts
  packages/plugins/aws-storage/tests/s3PackageManagerMockedS3.test.ts
  packages/plugins/aws-storage/tests/setConfigValue.test.ts
  packages/plugins/aws-storage/tsconfig.build.json
  packages/plugins/aws-storage/tsconfig.json
  pnpm-lock.yaml
Labels: hacktoberfest-accepted

#1973 eslint errors
  .changeset/three-pots-sit.md
  packages/api/src/publish.ts
  packages/api/src/star.ts
  packages/api/src/v1/search.ts
  packages/api/src/v1/token.ts
  packages/auth/src/auth.ts
  packages/auth/test/auth-utils.spec.ts
  packages/cli/src/cli.ts
  packages/cli/src/commands/init.ts
  packages/commons/src/constants.ts
  packages/commons/src/helpers/pkg.ts
  packages/config/src/config-path.ts
  packages/config/test/config.spec.ts
  packages/core/commons-api/src/index.ts
  packages/core/file-locking/tests/lock.spec.ts
  packages/core/htpasswd/tests/utils.test.ts
  packages/core/local-storage/src/local-database.ts
  packages/core/local-storage/src/pkg-utils.ts
  packages/core/local-storage/tests/__fixtures__/pkg.js
  packages/core/readme/tests/readme.spec.ts
  packages/core/types/index.d.ts
  packages/hooks/test/notify-request.spec.ts
  packages/loaders/src/plugin-loader.ts
  packages/logger-prettify/test/formatter.spec.ts
  packages/logger/src/logger.ts
  packages/middleware/src/middleware.ts
  packages/mock/src/server_process.ts
  packages/mock/src/utils-test.ts
  packages/node-api/src/bootstrap.ts
  packages/node-api/src/experiments.ts
  packages/node-api/src/https.ts
  packages/proxy/src/up-storage.ts
  packages/server/test/api/helpers/publish-api.js
  packages/server/test/api/helpers/utils.ts
  packages/server/test/api/index.spec.ts
  packages/server/test/api/plugin/filter.ts
  packages/server/test/jwt/index.spec.ts
  packages/server/test/storage/index.spec.ts
  packages/store/src/local-storage.ts
  packages/store/src/storage-utils.ts
  packages/store/src/storage.ts
  packages/store/test/local-storage.spec.ts
  packages/types/src/index.ts
  packages/utils/test/auth-utils.spec.ts
  packages/utils/test/config-utils.spec.ts
  packages/verdaccio/test/functional/lib/environment.ts
  packages/verdaccio/test/functional/package/scoped.ts
  packages/verdaccio/test/functional/sanity/incomplete.ts
  packages/verdaccio/test/functional/sanity/nullstorage.ts
  packages/verdaccio/test/functional/sanity/racycrash.ts
  packages/verdaccio/test/functional/sanity/security.ts
  packages/verdaccio/test/unit/__helper/__template/api.__test.ts
  packages/verdaccio/test/unit/__helper/utils.ts
Labels: hacktoberfest-accepted

#1978 refactor: relocate verdaccio-google-cloud-storage plugin
  packages/plugins/google-cloud-storage/.babelrc
  packages/plugins/google-cloud-storage/CHANGELOG.md
  packages/plugins/google-cloud-storage/LICENSE
  packages/plugins/google-cloud-storage/README.md
  packages/plugins/google-cloud-storage/jest.config.js
  packages/plugins/google-cloud-storage/package.json
  packages/plugins/google-cloud-storage/src/data-storage.ts
  packages/plugins/google-cloud-storage/src/index.ts
  packages/plugins/google-cloud-storage/src/storage-helper.ts
  packages/plugins/google-cloud-storage/src/storage.ts
  packages/plugins/google-cloud-storage/src/types/index.ts
  packages/plugins/google-cloud-storage/tests/datastore.spec.ts
  packages/plugins/google-cloud-storage/tests/partials/.eslintrc
  packages/plugins/google-cloud-storage/tests/partials/config.ts
  packages/plugins/google-cloud-storage/tests/partials/pkg.ts
  packages/plugins/google-cloud-storage/tests/partials/test-corrupt-pkg/corrupt.ts
  packages/plugins/google-cloud-storage/tests/partials/test-pkg/package.json
  packages/plugins/google-cloud-storage/tests/partials/test-pkg/test-pkg-1.0.0.tgz
  packages/plugins/google-cloud-storage/tests/partials/utils.helpers.ts
  packages/plugins/google-cloud-storage/tests/storage.spec.ts
  packages/plugins/google-cloud-storage/tsconfig.build.json
  packages/plugins/google-cloud-storage/tsconfig.json
  pnpm-lock.yaml
Labels: hacktoberfest-accepted

#1992 feat: update docker base image to node v14.15.0
  Dockerfile
Labels: Docker
