Repository verdaccio/verdaccio, pull requests merged in 2021-02, with the labels that each got.

#2076 ref: refactor utils methods
  packages/api/src/publish.ts
  packages/api/src/utils.ts
  packages/auth/src/auth.ts
  packages/auth/src/utils.ts
  packages/config/src/config-path.ts
  packages/config/src/config-utils.ts
  packages/middleware/src/middleware-utils.ts
  packages/middleware/src/middleware.ts
  packages/middleware/test/middleware-utils.spec.ts
  packages/proxy/src/proxy-utils.ts
  packages/proxy/src/up-storage.ts
  packages/proxy/test/proxy-utils.spec.ts
  packages/store/src/local-storage.ts
  packages/store/src/storage-utils.ts
  packages/store/test/storage-utils.spec.ts
  packages/utils/src/auth-utils.ts
  packages/utils/src/crypto-utils.ts
  packages/utils/src/utils.ts
  packages/utils/test/tag.version.spec.ts
  packages/utils/test/utils.spec.ts
  packages/web/src/endpoint/package.ts
  packages/web/src/render-web.ts
  packages/web/src/web-utils2.ts
  packages/web/test/web-utils.spec.ts
Labels: dev: refactor

#2104 fix: Upgrade Node from 14.15 to 14.16 for security fixes
  Dockerfile
Labels: Docker, security

#2109 chore: migrate e2e test to github actions
  .circleci/config.yml
  .github/workflows/ci-e2e-ui.yml
  .github/workflows/ci-e2e.yml
Labels: dev: ci-build
