Repository verdaccio/verdaccio, pull requests merged in 2021-10, with the labels that each got.

#2462 website: Improve docs link discoverability
  website/src/css/custom.scss
Labels: website, trigger-preview

#2466 ci: avoid crowdin step is mandatory
  .github/workflows/changesets.yml
  .github/workflows/ci.yml
Labels: dev: ci-build, topic: translations

#2465 refactor: Remove some FIXME annotations
  packages/core/local-storage/tests/__mocks__/Logger.ts
  packages/core/local-storage/tests/local-database.test.ts
  packages/core/local-storage/tests/local-fs.test.ts
  packages/core/local-storage/tests/token.test.ts
  packages/core/local-storage/tests/utils.test.ts
  packages/middleware/src/middleware-utils.ts
Labels: dev: refactor, hacktoberfest-accepted

#2613 feat: migrate readme to fastify
  packages/core/server/package.json
  packages/core/server/src/routes/web/api/readme.ts
  packages/core/server/src/server.ts
  pnpm-lock.yaml
Labels: hacktoberfest-accepted, fastify migration

#2615 use warning code for deprecation warnings
  packages/cli/src/commands/FastifyServer.ts
Labels: hacktoberfest-accepted
