Repository verdaccio/verdaccio, pull requests merged in 2021-12, with the labels that each got.

#2701 improve website contributors page docusaurus
  .github/workflows/website.yml
  packages/tools/docusaurus-plugin-contributors/.babelrc
  packages/tools/docusaurus-plugin-contributors/README.md
  packages/tools/docusaurus-plugin-contributors/package.json
  packages/tools/docusaurus-plugin-contributors/src/contributors.json
  packages/tools/docusaurus-plugin-contributors/src/index.ts
  packages/tools/docusaurus-plugin-contributors/tsconfig.build.json
  packages/tools/docusaurus-plugin-contributors/tsconfig.json
  pnpm-lock.yaml
  website/docusaurus.config.js
  website/package.json
  website/src/components/Contributors.tsx
  website/src/pages/contributors.module.scss
  website/src/pages/contributors.tsx
Labels: website

#2722 Update how-to-deploy-on-AWS.md
  website/docs/how-to-deploy-on-AWS.md
Labels: docs

#2727 fix: Markdown anchor links in package readMe.md broken #2712
  .pnp.js
  .yarn/cache/@verdaccio-readme-npm-10.0.1-dd3c1c7def-fa9671f10d.zip
  .yarn/cache/@verdaccio-readme-npm-10.1.0-b5e92d038e-0d116bbd32.zip
  package.json
  src/api/web/endpoint/package.ts
  src/lib/utils.ts
  yarn.lock
Labels: pending 6.x, topic: readme

#2655 Add params validation for sidebar fastify web endpoints
  packages/core/server/src/routes/web/api/sidebar.ts
Labels: fastify migration

#2750 refactor: download manifest endpoint and integrate fastify
  .changeset/bright-poems-obey.md
  .changeset/pretty-hounds-tap.md
  .github/workflows/ci.yml
  .prettierignore
  packages/api/package.json
  packages/api/src/index.ts
  packages/api/src/package.ts
  packages/core/server/src/endpoints/package.ts
  packages/core/server/src/server.ts
  packages/core/tarball/src/index.ts
  packages/plugins/local-storage/package.json
  packages/plugins/local-storage/src/local-fs.ts
  packages/plugins/memory/src/memory-handler.ts
  packages/store/package.json
  packages/store/src/local-storage.ts
  packages/store/src/storage.ts
  packages/store/src/type.ts
  packages/store/test/search.spec.ts
  packages/store/test/storage.spec.ts
  packages/tools/mock/package.json
  packages/tools/mock/src/config.ts
  packages/utils/src/versions.ts
  packages/verdaccio/package.json
  pnpm-lock.yaml
Labels: feat: storage, feat: breaking-change, fastify migration

#2776 chore: update pnpm on ci
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
Labels: dev: ci-build

#2771 fix: publish with deprecated field
  src/api/endpoint/api/publish.ts
  test/unit/modules/api/api.spec.ts
Labels: cmd: publish, 5.x branch, cmd: npm deprecate

#2787 feat: jwt default time new set
  src/lib/auth-utils.ts
  src/lib/constants.ts
Labels: security, 5.x branch

#2793 feat: user agent is the client by default
  src/api/index.ts
  src/lib/config.ts
  src/lib/up-storage.ts
Labels: topic: proxy, security, pending 6.x

#2795 build: enable Node 17 on CI and npm8 on E2E
  .github/workflows/ci.yml
  .github/workflows/e2e-angular-cli-workflow.yml
  .github/workflows/e2e-gatsbyjs-cli-workflow.yml
  .github/workflows/e2e-jest-workflow.yml
  .pnp.js
  .vscode/launch.json
  test/test.conf.js
  test/unit/modules/api/api.search.spec.ts
  test/unit/modules/storage/store.spec.ts
  test/unit/modules/uplinks/up-storage.spec.ts
Labels: dev: ci-build

#2799 feat: add rate limiting to web endpoints
  .pnp.js
  .yarn/cache/@types-express-npm-4.17.11-1b3f17f056-2818120a0f.zip
  .yarn/cache/@types-express-npm-4.17.13-0e12fe9c24-9f17da703d.zip
  .yarn/cache/@types-express-npm-4.17.6-e48d33b003-45e31c66a0.zip
  .yarn/cache/@types-express-rate-limit-npm-5.1.3-9d611672fc-4b9d7d7bbb.zip
  .yarn/cache/@types-express-serve-static-core-npm-4.17.13-864c105004-6db6f2e0eb.zip
  .yarn/cache/@types-express-serve-static-core-npm-4.17.19-3f514f7e12-b6c8c357c5.zip
  .yarn/cache/@types-express-serve-static-core-npm-4.17.26-e4eb025705-0026cc244f.zip
  .yarn/cache/@types-mime-npm-1.3.2-ea71878ab3-c354bc1356.zip
  .yarn/cache/@types-mime-npm-2.0.1-1018885da5-61a328979f.zip
  .yarn/cache/@types-serve-static-npm-1.13.5-9e6c8c7261-1d4e222e24.zip
  .yarn/cache/@types-serve-static-npm-1.13.9-59107a68c3-f261127514.zip
  .yarn/cache/content-disposition-npm-0.5.4-2d93678616-44169dbbfd.zip
  .yarn/cache/cookie-npm-0.4.1-cc5e2ebb42-b8e0928e3e.zip
  .yarn/cache/express-npm-4.17.2-fd936fc165-dc1fdb3f85.zip
  .yarn/cache/express-rate-limit-npm-5.5.1-3af8247282-445fc5b6bc.zip
  .yarn/cache/forwarded-npm-0.2.0-6473dabe35-1e84548d8f.zip
  .yarn/cache/ipaddr.js-npm-1.9.1-19ae7878b4-de15bc7e63.zip
  .yarn/cache/ms-npm-2.1.3-81ff3cfac1-6e721e648a.zip
  .yarn/cache/proxy-addr-npm-2.0.7-dae6552872-ad78682246.zip
  .yarn/cache/safe-buffer-npm-5.2.1-3481c8aa9b-0bb57f0d8f.zip
  .yarn/cache/send-npm-0.17.2-73a3dbeba6-b47bfc0b79.zip
  .yarn/cache/serve-static-npm-1.14.2-3ce50bb5ff-5a38fdf841.zip
  conf/default.yaml
  conf/docker.yaml
  package.json
  src/api/web/endpoint/user.ts
  src/api/web/index.ts
  test/unit/modules/web/api.web.spec.ts
  test/unit/partials/config/yaml/api.spec.yaml
  test/unit/partials/config/yaml/api.web.spec.yaml
  test/unit/partials/config/yaml/default.yaml
  test/unit/partials/config/yaml/profile/profile.yaml
  yarn.lock
Labels: topic: web, security

#2800 feat: add rate limit to user api endpoints
  src/api/endpoint/api/user.ts
  src/api/endpoint/api/v1/index.ts
  src/api/endpoint/api/v1/profile.ts
  src/api/endpoint/api/v1/token.ts
  src/api/endpoint/index.ts
  src/api/user-rate-limit.ts
  src/api/web/api.ts
  src/api/web/endpoint/user.ts
Labels: topic: token, security, pending 6.x

#2803 feat: allow override user rate limit and user agent
  .github/workflows/e2e-jest-workflow.yml
  .pnp.js
  .yarn/cache/@verdaccio-types-npm-10.2.2-3a8a5ff733-cd16cad480.zip
  .yarn/cache/@verdaccio-types-npm-9.7.2-9a89bfb123-ad04a1cd1f.zip
  .yarn/cache/@verdaccio-ui-theme-npm-3.2.1-86c131bd8f-bd0c23b2ff.zip
  .yarn/cache/@verdaccio-ui-theme-npm-3.4.1-ff9f347e40-9873985e77.zip
  package.json
  src/api/endpoint/api/user.ts
  src/api/endpoint/api/v1/index.ts
  src/api/endpoint/api/v1/profile.ts
  src/api/endpoint/api/v1/token.ts
  src/api/endpoint/index.ts
  src/api/index.ts
  src/api/rate-limiter.ts
  src/api/user-rate-limit.ts
  src/api/web/api.ts
  src/api/web/endpoint/index.ts
  src/api/web/endpoint/package.ts
  src/api/web/endpoint/search.ts
  src/api/web/endpoint/user.ts
  src/api/web/index.ts
  src/lib/auth-utils.ts
  src/lib/config.ts
  src/lib/up-storage.ts
  src/lib/utils.ts
  test/e2e/e2e.spec.js
  test/e2e/setup.js
  test/lib/request.ts
  test/unit/modules/api/token.spec.ts
  test/unit/modules/web/api.web.spec.ts
  types/index.ts
  yarn.lock
Labels: security, 5.x branch, pending 6.x

#2833 feat!: Node v16 as minimum for verdaccio 6
  .babelrc
  .github/workflows/ci.yml
  Dockerfile
  README.md
Labels: feat: breaking-change

#2835 feat: upgrade to pino v7
  .changeset/thick-countries-move.md
  packages/logger-prettify/package.json
  packages/logger/package.json
  pnpm-lock.yaml
Labels: topic: logging
