Repository verdaccio/verdaccio, pull requests merged in 2021-11, with the labels that each got.

#2624 feat: migrate web login endpoint to fastify
  packages/auth/src/auth.ts
  packages/auth/test/auth.spec.ts
  packages/core/server/src/routes/web/api/login.ts
  packages/core/server/src/server.ts
  packages/web/test/helper.ts
Labels: fastify migration

#2638 dist-tags endpoint fastify
  .changeset/ten-parents-breathe.md
  packages/core/server/src/endpoints/dist-tags.ts
  packages/core/server/src/plugins/coreUtils.ts
  packages/core/server/src/server.ts
Labels: fastify migration

#2650 refactor: improve versions and dist-tag filters
  .changeset/three-moles-drop.md
  package.json
  packages/api/src/package.ts
  packages/store/src/storage-utils.ts
  packages/store/src/storage.ts
  packages/utils/src/index.ts
  packages/utils/src/utils.ts
  packages/utils/src/versions.ts
  packages/utils/test/utils.spec.ts
  packages/utils/test/versions.spec.ts
Labels: dev: refactor, deprecation

#2654 fix initialization storage on fastify
  packages/core/server/src/plugins/storage.ts
Labels: bug: fixed, fastify migration

#2652 fix: hydrate template placeholders in JSON log messages
  .changeset/fair-lemons-beam.md
  packages/logger-prettify/src/index.ts
  packages/logger/src/logger.ts
Labels: topic: logging

#2667 workaround for invalid checksum
  website/docs/reverse-proxy.md
Labels: docs

#2687 migrate docker-https-portal example from V4 to V6
  docker-examples/v6/README.md
  docker-examples/v6/https-portal-example/README.md
  docker-examples/v6/https-portal-example/conf/config.yaml
  docker-examples/v6/https-portal-example/conf/htpasswd
  docker-examples/v6/https-portal-example/docker-compose.yml
  docker-examples/v6/https-portal-example/storage/@scope/example/example-1.0.0.tgz
  docker-examples/v6/https-portal-example/storage/@scope/example/package.json
  docker-examples/v6/https-portal-example/storage/jquery/package.json
Labels: docker-examples
