Repository verdaccio/verdaccio, pull requests merged in 2021-04, with the labels that each got.

#2156 feat: custom protocol header
  docs/env.variables.md
  src/lib/utils.ts
  test/unit/modules/utils/utils.spec.ts
Labels: topic: feature request

#2160 feat: clipanion as cli
  package.json
  src/api/endpoint/api/package.ts
  src/api/endpoint/api/publish.ts
  src/api/index.ts
  src/api/middleware.ts
  src/lib/cli.ts
  src/lib/cli/cli.ts
  src/lib/cli/commands/info.ts
  src/lib/cli/commands/init.ts
  src/lib/cli/commands/version.ts
  src/lib/cli/utils.ts
  src/lib/config-path.ts
  src/lib/storage-utils.ts
  src/lib/up-storage.ts
  src/lib/utils.ts
  test/e2e-cli/utils/registry.ts
  test/functional/package/gzip.ts
  test/functional/tags/addtag.ts
  test/lib/server.ts
  tsconfig.json
  types/custom.d.ts
  yarn.lock
Labels: dev: cli, topic: feature request

#2165 feat: improve node-api
  .changeset/two-dolls-check.md
  packages/cli/src/commands/init.ts
  packages/config/src/config-path.ts
  packages/core/types/index.d.ts
  packages/logger/src/logger.ts
  packages/node-api/examples/.eslintrc
  packages/node-api/examples/default.configuration.example.js
  packages/node-api/jest.config.js
  packages/node-api/package.json
  packages/node-api/src/bootstrap.d.ts
  packages/node-api/src/bootstrap.ts
  packages/node-api/src/cli-utils.ts
  packages/node-api/src/index.ts
  packages/node-api/src/server.ts
  packages/node-api/test/node-api.spec.ts
  packages/node-api/test/run-server.spec.ts
  packages/plugins/google-cloud-storage/tests/datastore.spec.ts
  packages/verdaccio/src/index.ts
  pnpm-lock.yaml
  src/api/web/html/favicon.ico
  src/api/web/html/manifest.ts
  src/api/web/html/renderHTML.ts
  src/api/web/html/template.ts
  src/lib/cli/cli.ts
  src/lib/cli/commands/info.ts
  src/lib/cli/commands/init.ts
  src/lib/cli/commands/version.ts
  src/lib/logger/formatter/index.ts
  src/lib/logger/formatter/prettifier.ts
  src/lib/logger/index.ts
  src/lib/logger/logger.ts
Labels: dev: cli, feat: breaking-change

#2199 feat: environment variables support in configuration file
  .changeset/healthy-poets-compare.md
  docs/env.variables.md
  packages/config/src/config.ts
  packages/config/test/config-parsing.spec.ts
  packages/config/test/config.spec.ts
  packages/config/test/package-access.spec.ts
  packages/config/test/partials/config/yaml/storage.yaml
  packages/config/test/uplinks.spec.ts
  packages/config/test/utils/index.ts
  packages/config/test/utils/parse-configuration-file.ts
Labels: topic: feature request

#2202 fix: restore logger on init
  .changeset/healthy-bikes-behave.md
  .changeset/pre.json
  packages/cli/package.json
  packages/cli/src/cli.ts
  packages/cli/src/commands/init.ts
  packages/cli/tsconfig.json
  packages/core/cli-ui/.babelrc
  packages/core/cli-ui/.eslintrc
  packages/core/cli-ui/jest.config.js
  packages/core/cli-ui/package.json
  packages/core/cli-ui/src/index.tsx
  packages/core/cli-ui/src/messages.tsx
  packages/core/cli-ui/tests/cli.spec.ts
  packages/core/cli-ui/tsconfig.build.json
  packages/core/cli-ui/tsconfig.json
  packages/core/types/index.d.ts
  packages/node-api/package.json
  packages/node-api/src/experiments.ts
  packages/node-api/src/server.ts
  packages/server/src/server.ts
  pnpm-lock.yaml
Labels: issue: bug, topic: logging

#2205 fix: incorrect sanity check for theme plugin
  src/api/web/index.ts
Labels: plugins

#2207 fix: update @verdaccio/ui-theme
  package.json
  yarn.lock
Labels: 5.x branch

#2208 fix: scoped query support
  src/lib/search.ts
  test/unit/modules/search/search.spec.ts
  test/unit/modules/web/api.web.spec.ts
Labels: 5.x branch
