Repository verdaccio/verdaccio, pull requests merged in 2021-09, with the labels that each got.

#2395 Update many package deps including babel, @types & more
  .project
  package.json
  packages/api/package.json
  packages/core/htpasswd/package.json
  packages/hooks/package.json
  packages/logger-prettify/package.json
  packages/mock/package.json
  packages/node-api/package.json
  packages/plugins/memory/package.json
  packages/plugins/ui-theme/package.json
  packages/standalone/package.json
  packages/tools/benchmark/package.json
  pnpm-lock.yaml
  test/e2e-cli/package.json
  test/e2e-ui/package.json
  website/package.json
Labels: dependencies

#2398 Indiescripter/align website format lint configs
  .eslintignore
  .npmignore
  .prettierrc
  package.json
  packages/cli/package.json
  packages/core/commons-api/package.json
  packages/core/readme/package.json
  packages/core/server/package.json
  packages/hooks/package.json
  packages/logger-prettify/package.json
  packages/logger/package.json
  packages/middleware/src/middleware.ts
  packages/plugins/audit/package.json
  packages/plugins/aws-storage/package.json
  packages/plugins/memory/package.json
  packages/plugins/ui-theme/package.json
  packages/server/package.json
  packages/tools/benchmark/package.json
  packages/verdaccio/test/jest.config.functional.js
  packages/web/package.json
  pnpm-lock.yaml
  test/e2e-cli/package.json
  website/.eslintrc.js
  website/.prettierrc
  website/package.json
  website/src/components/Command.tsx
  website/src/components/Divider.tsx
  website/src/components/Features.tsx
  website/src/components/Header.tsx
  website/src/components/PackageManagers.tsx
  website/src/components/Spinner.module.scss
  website/src/components/Testimonials.tsx
  website/src/components/TwitterCarrousel.tsx
  website/src/components/UsedBy.tsx
  website/src/components/WhatIsVerdaccio.tsx
  website/src/pages/contributors.tsx
  website/src/pages/help.tsx
Labels: dependencies

#2402 build: remove some unused dependencies
  package.json
  packages/logger-prettify/package.json
  packages/node-api/package.json
  pnpm-lock.yaml
Labels: dependencies

#2401 Indiescripter/update mostly e2e test deps
  packages/plugins/aws-storage/package.json
  pnpm-lock.yaml
  test/e2e-ui/package.json
Labels: dependencies

#2403 Indiescripter/update ui-theme package deps
  packages/config/package.json
  packages/plugins/ui-theme/package.json
  pnpm-lock.yaml
Labels: dependencies

#2408 Indiescripter/update misc deps
  packages/cli/package.json
  packages/plugins/google-cloud-storage/package.json
  packages/types/package.json
  pnpm-lock.yaml
  test/e2e-cli/package.json
  test/e2e-ui/package.json
  website/package.json
Labels: dependencies

#2409 Indiescripter/upgrade webpack
  package.json
  packages/plugins/ui-theme/package.json
  packages/standalone/package.json
  pnpm-lock.yaml
Labels: dependencies

#2410 Indiescripter/upgrade husky
  package.json
  pnpm-lock.yaml
Labels: dependencies

#2418 fix(core/hooks/mock/node-api): add missing core-js dep
  .changeset/proud-jeans-walk.md
  packages/core/htpasswd/package.json
  packages/core/local-storage/package.json
  packages/core/server/package.json
  packages/hooks/package.json
  packages/mock/package.json
  packages/node-api/package.json
  pnpm-lock.yaml
Labels: dependencies

#2414 Indiescripter/upgrade website docusaurus
  package.json
  pnpm-lock.yaml
  website/package.json
Labels: dependencies, website

#2422 Indiescripter/last misc deps update for now
  package.json
  packages/core/htpasswd/package.json
  packages/core/local-storage/package.json
  packages/core/server/package.json
  packages/hooks/package.json
  packages/mock/package.json
  packages/node-api/package.json
  packages/plugins/active-directory/package.json
  packages/plugins/memory/package.json
  packages/plugins/ui-theme/package.json
  packages/standalone/package.json
  pnpm-lock.yaml
  test/e2e-cli/package.json
Labels: dependencies

#2426 fix: npm7 audit fix and bulk endpoint
  .github/workflows/docker-publish-pre-check.yml
  .pnp.js
  .yarn/cache/node-fetch-npm-2.6.0-29c7a53447-dd9f586a9f.zip
  .yarn/cache/verdaccio-audit-npm-10.0.0-449c810834-60969a3c26.zip
  .yarn/cache/verdaccio-audit-npm-10.0.1-b900394416-1b3203c893.zip
  .yarnrc.yml
  Dockerfile
  package.json
  yarn.lock
Labels: topic: npm7, topic: audit

#2432 feat: fastify search endpoint v1 without auth and format
  packages/core/server/src/endpoints/search.ts
Labels: fastify migration

#2436 Upgrade to husky@7.0.2
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: dependencies, dev: lint

#2439 refactor: replace flag icons with library
  crowdin.yaml
  packages/plugins/ui-theme/i18n/config.ts
  packages/plugins/ui-theme/package.json
  packages/plugins/ui-theme/src/App/App.tsx
  packages/plugins/ui-theme/src/App/Footer/Footer.tsx
  packages/plugins/ui-theme/src/App/Footer/__snapshots__/Footer.test.tsx.snap
  packages/plugins/ui-theme/src/App/Header/Header.test.tsx
  packages/plugins/ui-theme/src/App/Header/LanguageSwitch.tsx
  packages/plugins/ui-theme/src/components/Icons/Austria.tsx
  packages/plugins/ui-theme/src/components/Icons/Brazil.tsx
  packages/plugins/ui-theme/src/components/Icons/China.tsx
  packages/plugins/ui-theme/src/components/Icons/Czech.tsx
  packages/plugins/ui-theme/src/components/Icons/France.tsx
  packages/plugins/ui-theme/src/components/Icons/Germany.tsx
  packages/plugins/ui-theme/src/components/Icons/India.tsx
  packages/plugins/ui-theme/src/components/Icons/Japan.tsx
  packages/plugins/ui-theme/src/components/Icons/Khmer.tsx
  packages/plugins/ui-theme/src/components/Icons/Nicaragua.tsx
  packages/plugins/ui-theme/src/components/Icons/Russia.tsx
  packages/plugins/ui-theme/src/components/Icons/Spain.tsx
  packages/plugins/ui-theme/src/components/Icons/Taiwan.tsx
  packages/plugins/ui-theme/src/components/Icons/Turkey.tsx
  packages/plugins/ui-theme/src/components/Icons/Ukraine.tsx
  packages/plugins/ui-theme/src/components/Icons/Usa.tsx
  packages/plugins/ui-theme/src/components/Icons/index.ts
  packages/plugins/ui-theme/src/design-tokens/ThemeContext.ts
  packages/plugins/ui-theme/src/i18n/config.ts
  packages/plugins/ui-theme/src/i18n/enabledLanguages.ts
  packages/plugins/ui-theme/src/i18n/translations/cs-CZ.json
  packages/plugins/ui-theme/src/i18n/translations/de-DE.json
  packages/plugins/ui-theme/src/i18n/translations/en-US.json
  packages/plugins/ui-theme/src/i18n/translations/es-ES.json
  packages/plugins/ui-theme/src/i18n/translations/fr-FR.json
  packages/plugins/ui-theme/src/i18n/translations/ja-JP.json
  packages/plugins/ui-theme/src/i18n/translations/km-KH.json
  packages/plugins/ui-theme/src/i18n/translations/pt-BR.json
  packages/plugins/ui-theme/src/i18n/translations/ru-RU.json
  packages/plugins/ui-theme/src/i18n/translations/tr-TR.json
  packages/plugins/ui-theme/src/i18n/translations/uk-UA.json
  packages/plugins/ui-theme/src/i18n/translations/zh-CN.json
  packages/plugins/ui-theme/src/i18n/translations/zh-TW.json
  packages/plugins/ui-theme/src/pages/Version/DetailContainer/Versions/Versions.test.tsx
  packages/plugins/ui-theme/src/pages/Version/Version.test.tsx
  packages/plugins/ui-theme/src/utils/test-react-testing-library.tsx
  packages/plugins/ui-theme/tsconfig.json
  pnpm-lock.yaml
Labels: dev: refactor

#2442 refactor: using ui translations from crowdin
  .github/workflows/ci.yml
  .gitignore
  packages/plugins/ui-theme/src/App/Header/Header.test.tsx
  packages/plugins/ui-theme/src/i18n/config.ts
  packages/plugins/ui-theme/src/i18n/crowdin/ABOUT_TRANSLATIONS.md
  packages/plugins/ui-theme/src/i18n/deprecated_translations_dont_use/cs-CZ.json
  packages/plugins/ui-theme/src/i18n/deprecated_translations_dont_use/de-DE.json
  packages/plugins/ui-theme/src/i18n/deprecated_translations_dont_use/en-US.json
  packages/plugins/ui-theme/src/i18n/deprecated_translations_dont_use/es-ES.json
  packages/plugins/ui-theme/src/i18n/deprecated_translations_dont_use/fr-FR.json
  packages/plugins/ui-theme/src/i18n/deprecated_translations_dont_use/ja-JP.json
  packages/plugins/ui-theme/src/i18n/deprecated_translations_dont_use/km-KH.json
  packages/plugins/ui-theme/src/i18n/deprecated_translations_dont_use/pt-BR.json
  packages/plugins/ui-theme/src/i18n/deprecated_translations_dont_use/ru-RU.json
  packages/plugins/ui-theme/src/i18n/deprecated_translations_dont_use/tr-TR.json
  packages/plugins/ui-theme/src/i18n/deprecated_translations_dont_use/uk-UA.json
  packages/plugins/ui-theme/src/i18n/deprecated_translations_dont_use/zh-CN.json
  packages/plugins/ui-theme/src/i18n/deprecated_translations_dont_use/zh-TW.json
  packages/plugins/ui-theme/src/pages/Version/DetailContainer/Versions/Versions.test.tsx
  packages/plugins/ui-theme/src/pages/Version/Version.test.tsx
  packages/plugins/ui-theme/src/pages/home/PackageList/Help/__snapshots__/Help.test.tsx.snap
Labels: topic: ui

#2445 rename translation file
  .gitignore
  CONTRIBUTING.md
  crowdin.yaml
  packages/plugins/ui-theme/src/App/Header/Header.test.tsx
  packages/plugins/ui-theme/src/i18n/ABOUT_TRANSLATIONS.md
  packages/plugins/ui-theme/src/i18n/config.ts
  packages/plugins/ui-theme/src/i18n/crowdin/ui.json
  packages/plugins/ui-theme/src/pages/Version/DetailContainer/Versions/Versions.test.tsx
  packages/plugins/ui-theme/src/pages/Version/Version.test.tsx
  packages/plugins/ui-theme/src/utils/login.test.ts
Labels: topic: ui, topic: translations

#2446 fix: do not throw multiple logger deprecation warning if using default logger config
  .changeset/shaggy-carrots-unite.md
  packages/logger/src/logger.ts
  packages/logger/test/logger.spec.ts
Labels: bug: fixed

#2447 refactor: rematch as web state storage for UI
  .changeset/olive-candles-speak.md
  .gitignore
  package.json
  packages/plugins/ui-theme/jest/api/packages.json
  packages/plugins/ui-theme/jest/jest.config.js
  packages/plugins/ui-theme/jest/server-handlers.ts
  packages/plugins/ui-theme/jest/server.ts
  packages/plugins/ui-theme/jest/setup-env.ts
  packages/plugins/ui-theme/jest/setup.ts
  packages/plugins/ui-theme/package.json
  packages/plugins/ui-theme/src/App/App.test.tsx
  packages/plugins/ui-theme/src/App/App.tsx
  packages/plugins/ui-theme/src/App/AppContext.ts
  packages/plugins/ui-theme/src/App/AppContextProvider.tsx
  packages/plugins/ui-theme/src/App/AppRoute.tsx
  packages/plugins/ui-theme/src/App/Header/Header.test.tsx
  packages/plugins/ui-theme/src/App/Header/Header.tsx
  packages/plugins/ui-theme/src/App/Header/HeaderMenu.tsx
  packages/plugins/ui-theme/src/App/Header/LoginDialog/LoginDialog.test.tsx
  packages/plugins/ui-theme/src/App/Header/LoginDialog/LoginDialog.tsx
  packages/plugins/ui-theme/src/App/Header/RegistryInfoContent/RegistryInfoContent.test.tsx
  packages/plugins/ui-theme/src/App/Header/Search/Search.test.tsx
  packages/plugins/ui-theme/src/App/Header/Search/Search.tsx
  packages/plugins/ui-theme/src/App/index.ts
  packages/plugins/ui-theme/src/components/ActionBar/ActionBar.test.tsx
  packages/plugins/ui-theme/src/components/ActionBar/ActionBarAction.tsx
  packages/plugins/ui-theme/src/components/Author/Author.test.tsx
  packages/plugins/ui-theme/src/i18n/config.ts
  packages/plugins/ui-theme/src/index.tsx
  packages/plugins/ui-theme/src/pages/Version/DetailContainer/UpLinks/UpLinks.test.tsx
  packages/plugins/ui-theme/src/pages/Version/DetailSidebar/ActionBar/ActionBar.test.tsx
  packages/plugins/ui-theme/src/pages/Version/DetailSidebar/ActionBar/__snapshots__/ActionBar.test.tsx.snap
  packages/plugins/ui-theme/src/pages/Version/Version.tsx
  packages/plugins/ui-theme/src/pages/Version/VersionContextProvider.tsx
  packages/plugins/ui-theme/src/pages/Version/is-package-version-valid.ts
  packages/plugins/ui-theme/src/pages/home/Home.tsx
  packages/plugins/ui-theme/src/pages/home/PackageList/Help/__snapshots__/Help.test.tsx.snap
  packages/plugins/ui-theme/src/pages/home/PackageList/Package/Package.test.tsx
  packages/plugins/ui-theme/src/pages/home/PackageList/Package/Package.tsx
  packages/plugins/ui-theme/src/pages/home/PackageList/PackageList.tsx
  packages/plugins/ui-theme/src/pages/home/PackageList/Packagelist.test.tsx
  packages/plugins/ui-theme/src/providers/API/APIProvider.tsx
  packages/plugins/ui-theme/src/providers/API/api.test.ts
  packages/plugins/ui-theme/src/providers/API/api.ts
  packages/plugins/ui-theme/src/providers/API/index.ts
  packages/plugins/ui-theme/src/store/index.ts
  packages/plugins/ui-theme/src/store/models/configuration.ts
  packages/plugins/ui-theme/src/store/models/download.ts
  packages/plugins/ui-theme/src/store/models/index.ts
  packages/plugins/ui-theme/src/store/models/login.ts
  packages/plugins/ui-theme/src/store/models/manifest.ts
  packages/plugins/ui-theme/src/store/models/packages.ts
  packages/plugins/ui-theme/src/store/models/search.ts
  packages/plugins/ui-theme/src/store/store.ts
  packages/plugins/ui-theme/src/utils/test-react-testing-library.tsx
  packages/plugins/ui-theme/tsconfig.json
  packages/plugins/ui-theme/types/index.ts
  packages/web/src/api/package.ts
  pnpm-lock.yaml
  test/e2e-ui/e2e.spec.js
Labels: topic: web
