Repository verdaccio/verdaccio, pull requests merged in 2022-08, with the labels that each got.

#3293 docs: fix typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs

#3308 feat: upgrade to pino 8 with async logging
  .changeset/clever-pugs-warn.md
  .gitignore
  packages/cli/src/commands/init.ts
  packages/core/core/src/warning-utils.ts
  packages/core/types/README.md
  packages/core/types/index.d.ts
  packages/core/types/package.json
  packages/core/types/src/commons.ts
  packages/core/types/src/configuration.ts
  packages/core/types/src/manifest.ts
  packages/core/types/src/plugins/auth.ts
  packages/core/types/src/plugins/commons.ts
  packages/core/types/src/plugins/filter.ts
  packages/core/types/src/plugins/index.ts
  packages/core/types/src/plugins/middleware.ts
  packages/core/types/src/plugins/storage.ts
  packages/core/types/src/plugins/theme.ts
  packages/core/types/src/search.ts
  packages/core/types/src/types.ts
  packages/core/types/tsconfig.build.json
  packages/core/types/tsconfig.json
  packages/core/types/typedoc.json
  packages/logger-prettify/jest.config.js
  packages/logger-prettify/package.json
  packages/logger-prettify/src/formatter.ts
  packages/logger-prettify/src/index.ts
  packages/logger-prettify/src/levels.ts
  packages/logger-prettify/src/prettify.ts
  packages/logger-prettify/src/types.ts
  packages/logger-prettify/src/utils.ts
  packages/logger-prettify/test/__snapshots__/formatter.spec.ts.snap
  packages/logger-prettify/test/__snapshots__/index.spec.ts.snap
  packages/logger-prettify/test/formatter.spec.ts
  packages/logger-prettify/test/index.spec.ts
  packages/logger-prettify/test/utils.test.ts
  packages/logger/package.json
  packages/logger/src/index.ts
  packages/logger/src/logger.ts
  packages/logger/test/createLogger.spec.ts
  packages/logger/test/logger.spec.ts
  packages/plugins/audit/src/audit.ts
  packages/tools/eslint/src/index.js
  packages/tools/mock/package.json
  pnpm-lock.yaml
Labels: topic: logging

#3310 chore: fix missing dep on master
  .github/workflows/ci.yml
  packages/logger-prettify/src/levels.ts
Labels: issue: bug

#3322 feat: implement abbreviated manifest
  .changeset/tricky-taxis-watch.md
  packages/api/src/package.ts
  packages/api/src/publish.ts
  packages/api/test/integration/package.spec.ts
  packages/core/types/src/manifest.ts
  packages/plugins/local-storage/src/local-database.ts
  packages/plugins/local-storage/src/local-fs.ts
  packages/server/fastify/src/endpoints/manifest.ts
  packages/server/fastify/src/routes/web/api/readme.ts
  packages/store/jest.config.js
  packages/store/src/lib/storage-utils.ts
  packages/store/src/storage.ts
  packages/store/src/type.ts
  packages/store/test/storage.spec.ts
  packages/tools/helpers/src/generatePackageMetadata.ts
  packages/verdaccio/test/unit/whoami.spec.ts
  packages/web/src/api/package.ts
  packages/web/src/api/readme.ts
Labels: topic: feature request

#3330 ui: basic grammatical fixes in the Ukraine Message
  .changeset/smooth-owls-pump.md
  packages/plugins/ui-theme/src/App/Header/Support/Support.tsx
Labels: topic: ui
