Repository verdaccio/verdaccio, pull requests merged in 2022-05, with the labels that each got.

#3151 fix: duplicated groups on use jwt tokens
  .github/workflows/e2e-jest-workflow.yml
  src/lib/auth-utils.ts
  src/lib/auth.ts
  test/unit/modules/auth/auth-utils.spec.ts
Labels: topic: token, pending 6.x

#3158 fix: remove lru deprecation warning
  src/api/web/html/renderHTML.ts
Labels: 5.x branch

#3200 fix: Fix storing same named files from different pkgs in memory plugin
  .changeset/chilled-ways-fetch.md
  packages/plugins/memory/src/memory-handler.ts
  packages/plugins/memory/test/memory.spec.ts
Labels: issue: bug, plugin: verdaccio-memory
