Repository verdaccio/verdaccio, pull requests merged in 2022-09, with the labels that each got.

#3340 fix: handle upload scoped tarball and add new deprecations
  .changeset/witty-ties-speak.md
  CONTRIBUTING.md
  package.json
  packages/api/src/package.ts
  packages/api/src/publish.ts
  packages/api/test/integration/config/publish-proxy.yaml
  packages/api/test/integration/package.spec.ts
  packages/api/test/integration/publish.spec.ts
  packages/api/test/integration/user.jwt.spec.ts
  packages/cli/src/commands/init.ts
  packages/core/core/src/warning-utils.ts
  packages/core/types/src/manifest.ts
  packages/store/src/storage.ts
  packages/store/test/storage.spec.ts
  packages/tools/helpers/jest.config.js
  packages/tools/helpers/src/generatePackageMetadata.ts
  packages/tools/helpers/src/jest.config.js
  packages/tools/helpers/tests/metadata.spec.ts
  packages/tools/local-publish/.babelrc
  packages/tools/local-publish/.eslintignore
  packages/tools/local-publish/.gitignore
  packages/tools/local-publish/LICENSE
  packages/tools/local-publish/package.json
  packages/tools/local-publish/src/.eslintrc
  packages/tools/local-publish/src/index.ts
  packages/tools/local-publish/tsconfig.build.json
  packages/tools/local-publish/tsconfig.json
  pnpm-lock.yaml
  test/cli/cli-commons/src/index.ts
  test/cli/cli-commons/src/registry.ts
  test/cli/cli-commons/src/utils.ts
  test/cli/e2e-npm6/info.spec.ts
  test/cli/e2e-npm6/publish.spec.ts
  test/cli/e2e-npm6/utils.ts
  test/cli/e2e-npm7/info.spec.ts
  test/cli/e2e-npm7/publish.spec.ts
  test/cli/e2e-npm7/utils.ts
  test/cli/e2e-npm8/info.spec.ts
  test/cli/e2e-npm8/publish.spec.ts
  test/cli/e2e-npm8/utils.ts
  test/cli/e2e-pnpm6/info.spec.ts
  test/cli/e2e-pnpm6/publish.spec.ts
  test/cli/e2e-pnpm6/utils.ts
  test/cli/e2e-pnpm7/info.spec.ts
  test/cli/e2e-pnpm7/publish.spec.ts
  test/cli/e2e-pnpm7/utils.ts
  test/cli/e2e-yarn1/info.spec.ts
  test/cli/e2e-yarn1/publish.spec.ts
  test/cli/e2e-yarn1/utils.ts
Labels: 6.x bugs, topic: maintenance

#3343 feat: implement abbreviated manifest
  .pnp.js
  .yarn/cache/@verdaccio-types-npm-10.5.2-df408a0b4b-60f8a1068b.zip
  .yarn/cache/@verdaccio-types-npm-10.6.0-31edb84449-7065a8551b.zip
  package.json
  src/api/endpoint/api/package.ts
  src/lib/storage-utils.ts
  src/lib/storage.ts
  test/unit/modules/api/api.spec.ts
  types/index.ts
  yarn.lock
Labels: topic: feature request, 5.x branch

#3347 fix: add missing fields to abbreviated metadata
  .pnp.js
  .yarn/cache/@verdaccio-types-npm-10.6.0-31edb84449-7065a8551b.zip
  .yarn/cache/@verdaccio-types-npm-10.7.0-28c6045ab8-5f88847bea.zip
  package.json
  src/lib/storage-utils.ts
  yarn.lock
Labels: issue: bug

#3359 fix: get header by quality priority value
  .github/workflows/e2e-gatsbyjs-cli-workflow.yml
  src/api/endpoint/api/package.ts
  src/utils/string.ts
  test/unit/modules/api/api.spec.ts
  test/unit/modules/utils/utils.spec.ts
Labels: issue: bug, pending 6.x

#3361 fix: abbreviated headers handle quality values
  .changeset/chilly-glasses-occur.md
  .changeset/config.json
  packages/api/src/package.ts
  packages/api/test/integration/package.spec.ts
  packages/core/core/src/constants.ts
  packages/core/core/src/index.ts
  packages/core/core/src/string-utils.ts
  packages/core/core/test/string-utils.spec.ts
  packages/server/fastify/src/endpoints/manifest.ts
  packages/store/src/storage.ts
Labels: 6.x bugs

#3383 test: add e2e for install
  pnpm-lock.yaml
  test/cli/README.md
  test/cli/cli-commons/src/index.ts
  test/cli/cli-commons/src/utils.ts
  test/cli/e2e-npm6/install.spec.ts
  test/cli/e2e-npm7/install.spec.ts
  test/cli/e2e-npm8/install.spec.ts
  test/cli/e2e-pnpm6/install.spec.ts
  test/cli/e2e-pnpm7/install.spec.ts
  test/cli/e2e-yarn1/install.spec.ts
  test/cli/e2e-yarn2/install.spec.ts
  test/cli/e2e-yarn2/yarn-install/.yarnrc.yml
  test/cli/e2e-yarn2/yarn-install/package.json
  test/cli/e2e-yarn2/yarn-install/yarn.lock
  test/cli/e2e-yarn3/install.spec.ts
  test/cli/e2e-yarn3/yarn-install/.yarnrc.yml
  test/cli/e2e-yarn3/yarn-install/package.json
  test/cli/e2e-yarn3/yarn-install/yarn.lock
  test/cli/e2e-yarn4/install.spec.ts
  test/cli/e2e-yarn4/yarn-install/.yarnrc.yml
  test/cli/e2e-yarn4/yarn-install/package.json
  test/cli/e2e-yarn4/yarn-install/yarn.lock
Labels: topic: maintenance

#3384 feat: add passwordValidationRegex property
  .changeset/shy-ducks-cover.md
  packages/api/src/index.ts
  packages/api/src/user.ts
  packages/api/src/v1/profile.ts
  packages/api/test/integration/user.jwt.spec.ts
  packages/api/test/integration/user.spec.ts
  packages/auth/src/auth.ts
  packages/config/src/conf/default.yaml
  packages/config/src/conf/docker.yaml
  packages/core/core/src/constants.ts
  packages/core/core/src/error-utils.ts
  packages/core/core/src/index.ts
  packages/core/core/src/validation-utils.ts
  packages/core/core/test/validation-utilts.spec.ts
  packages/core/types/src/configuration.ts
  packages/server/fastify/src/endpoints/user.ts
  packages/server/fastify/src/routes/web/api/login.ts
  packages/store/src/local-storage.ts
  packages/store/src/storage.ts
  packages/utils/jest.config.js
  packages/utils/src/auth-utils.ts
  packages/utils/test/auth-utils.spec.ts
  packages/web/src/api/user.ts
  packages/web/src/middleware/render-web.ts
Labels: topic: feature request, feat: auth

#3385 chore: re-stablished deprecated support
  .github/workflows/ci.yml
  .github/workflows/e2e-ci.yml
  packages/api/src/publish.ts
  packages/node-api/src/server.ts
  packages/store/jest.config.js
  packages/store/src/storage.ts
  packages/store/test/fixtures/config/deprecate.yaml
  packages/store/test/storage.spec.ts
  packages/tools/helpers/jest.config.js
  packages/tools/helpers/src/generatePackageMetadata.ts
  packages/tools/helpers/src/index.ts
  test/cli/README.md
  test/cli/cli-commons/src/process.ts
  test/cli/cli-commons/src/registry.ts
  test/cli/e2e-npm6/deprecate.spec.ts
  test/cli/e2e-npm6/jest.config.js
  test/cli/e2e-npm6/publish.spec.ts
  test/cli/e2e-npm7/deprecate.spec.ts
  test/cli/e2e-npm7/jest.config.js
  test/cli/e2e-npm8/deprecate.spec.ts
  test/cli/e2e-npm8/jest.config.js
  test/cli/e2e-pnpm6/deprecate.spec.ts
  test/cli/e2e-pnpm6/jest.config.js
  test/cli/e2e-pnpm7/deprecate.spec.ts
  test/cli/e2e-pnpm7/jest.config.js
  test/cli/e2e-yarn1/jest.config.js
  test/cli/e2e-yarn2/info.spec.ts
  test/cli/e2e-yarn2/install.spec.ts
  test/cli/e2e-yarn2/jest.config.js
  test/cli/e2e-yarn3/info.spec.ts
  test/cli/e2e-yarn3/install.spec.ts
  test/cli/e2e-yarn3/jest.config.js
  test/cli/e2e-yarn4/info.spec.ts
  test/cli/e2e-yarn4/install.spec.ts
  test/cli/e2e-yarn4/jest.config.js
  test/cli/jest.config.js
Labels: cmd: npm deprecate, topic: maintenance

#3405 fix: docker base image upgraded 14.20.1
  Dockerfile
Labels: 5.x branch

#3408 feat: Display publication time on sidebar
  .changeset/unlucky-hairs-wonder.md
  packages/plugins/ui-theme/src/i18n/crowdin/ui.json
  packages/plugins/ui-theme/src/pages/Version/DetailContainer/Versions/VersionsHistoryList.tsx
  packages/plugins/ui-theme/src/pages/Version/DetailSidebar/DetailSidebar.tsx
  packages/plugins/ui-theme/src/pages/Version/DetailSidebar/DetailSidebarTitle.tsx
Labels: topic: feature request, topic: web
