Repository verdaccio/verdaccio, pull requests merged in 2022-03, with the labels that each got.

#3011 feature: config control for colors in logs
  docs/env.variables.md
  src/lib/logger/formatter/index.ts
  src/lib/logger/formatter/prettifier.ts
  src/lib/logger/logger.ts
Labels: topic: feature request, topic: logging

#3025 Refactor htpasswd plugin to use use bcryptjs async API
  .changeset/swift-pumpkins-knock.md
  packages/auth/src/auth.ts
  packages/plugins/htpasswd/README.md
  packages/plugins/htpasswd/src/htpasswd.ts
  packages/plugins/htpasswd/src/utils.ts
  packages/plugins/htpasswd/tests/__fixtures__/htpasswd
  packages/plugins/htpasswd/tests/__mocks__/Logger.ts
  packages/plugins/htpasswd/tests/htpasswd.test.ts
  packages/plugins/htpasswd/tests/utils.test.ts
Labels: feat: auth, dev: code-review, bug: fixed

#3037 chore: migrate to fully undici fetch
  .github/workflows/ci.yml
  package.json
  packages/hooks/package.json
  packages/hooks/src/notify-request.ts
  packages/hooks/test/notify-request.spec.ts
  packages/plugins/htpasswd/tests/htpasswd.test.ts
  packages/proxy/package.json
  packages/proxy/src/up-storage.ts
  packages/proxy/test/proxy.search.spec.ts
  packages/store/package.json
  packages/store/test/search.spec.ts
  pnpm-lock.yaml
Labels: dev: migration, bot: dependencies

#3052 fix(loaders): always create plugin instance with new
  .changeset/lovely-drinks-argue.md
  packages/loaders/src/plugin-loader.ts
Labels: plugins, feat: breaking-change

#3097 config.logs throw an error, logging config not longer accept array or…
  .changeset/proud-jobs-hope.md
  docker-examples/v6/reverse_proxy/nginx/relative_path/conf/v6/config.yaml
  docker-examples/v6/reverse_proxy/nginx/relative_path/conf/v6_root/config.yaml
  docs/warnings.md
  package.json
  packages/api/test/integration/config/package.yaml
  packages/api/test/integration/config/ping.yaml
  packages/api/test/integration/config/publish.yaml
  packages/api/test/integration/config/user.yaml
  packages/api/test/integration/config/whoami.yaml
  packages/cli/src/commands/FastifyServer.ts
  packages/cli/src/commands/init.ts
  packages/config/src/conf/default.yaml
  packages/config/src/conf/docker.yaml
  packages/config/test/config.spec.ts
  packages/config/test/partials/config/js/default.js
  packages/config/test/partials/config/yaml/storage.yaml
  packages/core/core/src/warning-utils.ts
  packages/core/types/index.d.ts
  packages/logger/package.json
  packages/logger/src/logger.ts
  packages/logger/test/logger.spec.ts
  packages/node-api/src/server.ts
  packages/plugins/aws-storage/tests/__mocks__/Config.ts
  packages/plugins/google-cloud-storage/tests/partials/config.ts
  packages/plugins/htpasswd/tests/__fixtures__/config.yaml
  packages/plugins/htpasswd/tests/__mocks__/Config.js
  packages/plugins/local-storage/tests/__mocks__/Config.ts
  packages/plugins/memory/test/partials/config.ts
  packages/plugins/ui-theme/tools/_verdaccio.config.yaml
  packages/proxy/test/conf/proxy1.yaml
  packages/server/test/api/api.spec.yaml
  packages/server/test/basic/basic.yaml
  packages/server/test/jwt/jwt.yaml
  packages/server/test/package-access/pkg.access.yaml
  packages/server/test/profile/profile.yaml
  packages/server/test/storage/store.spec.yaml
  packages/server/test/token/token.spec.yaml
  packages/server/test/web/web.yaml
  packages/tools/mock/src/config/yaml/default.yaml
  packages/tools/mock/src/config/yaml/mock-server-test.yaml
  packages/tools/mock/test/config/yaml/default.yaml
  packages/verdaccio/test/README.md
  packages/verdaccio/test/functional/store/server1/config-1.yaml
  packages/verdaccio/test/functional/store/server2/config-2.yaml
  packages/verdaccio/test/functional/store/server3/config-3.yaml
  packages/verdaccio/test/unit/partials/config/yaml/api.spec/web-config.yaml
  packages/web/test/config/default-test.yaml
  packages/web/test/config/login-disabled.yaml
  pnpm-lock.yaml
  scripts/e2e-config.yaml
  test/e2e-cli/config/_bootstrap_verdaccio.yaml
  test/e2e-ui/config/config-protected-e2e.yaml
  test/e2e-ui/config/config-scoped-e2e.yaml
  website/docs/config.md
  website/docs/logger.md
  website/docs/node-api.md
Labels: topic: logging
