Repository verdaccio/verdaccio, pull requests merged in 2022-02, with the labels that each got.

#2993 feat: new environment variable (storage path)
  docs/env.variables.md
  src/lib/config.ts
  test/unit/modules/config/config.spec.ts
Labels: topic: feature request, feat: storage

#3013 fix: specific version package detail page not showing
  .changeset/spicy-snakes-sip.md
  packages/plugins/ui-theme/src/store/models/manifest.ts
Labels: topic: web

#3015 feat: add icons for module and typescript support
  .changeset/kind-bears-nail.md
  packages/plugins/ui-theme/jest/jest.config.js
  packages/plugins/ui-theme/src/components/Icons/DevsIcons/CommonJS.tsx
  packages/plugins/ui-theme/src/components/Icons/DevsIcons/ES6Module.tsx
  packages/plugins/ui-theme/src/components/Icons/DevsIcons/TypeScript.tsx
  packages/plugins/ui-theme/src/components/Icons/DevsIcons/commonjs.svg
  packages/plugins/ui-theme/src/components/Icons/DevsIcons/es6modules.svg
  packages/plugins/ui-theme/src/components/Icons/DevsIcons/index.tsx
  packages/plugins/ui-theme/src/components/Icons/DevsIcons/typescript.svg
  packages/plugins/ui-theme/src/components/Icons/index.ts
  packages/plugins/ui-theme/src/pages/Version/DetailSidebar/DetailSidebar.test.tsx
  packages/plugins/ui-theme/src/pages/Version/DetailSidebar/DetailSidebar.tsx
  packages/plugins/ui-theme/src/pages/Version/DetailSidebar/DetailSidebarTitle.tsx
  packages/plugins/ui-theme/types/packageMeta.ts
Labels: topic: feature request, topic: web
