Repository verdaccio/verdaccio, pull requests merged in 2023-01, with the labels that each got.

#3553 docs: add ui components docs
  packages/ui-components/src/Text/Text.tsx
  packages/ui-components/src/Text/index.ts
  website/docs/ui-components.md
  website/docs/web.md
  website/package.json
  website/sidebars.js
  website/versioned_docs/version-5.x/web.md
Labels: docs

#3554 updated gitlab auth (docker)
  website/docs/docker.md
Labels: docs

#3556 fix: include build types and systemd
  .github/workflows/release.yml
  .npmignore
Labels: 5.x branch

#3570 fix: improve support for fs promises older nodejs
  .changeset/chatty-pillows-perform.md
  packages/api/test/integration/_helper.ts
  packages/config/package.json
  packages/config/test/config-parsing.spec.ts
  packages/core/core/package.json
  packages/core/core/src/file-utils.ts
  packages/core/file-locking/package.json
  packages/core/file-locking/src/utils.ts
  packages/core/tarball/package.json
  packages/core/types/package.json
  packages/core/url/package.json
  packages/hooks/package.json
  packages/loaders/package.json
  packages/loaders/src/plugin-async-loader.ts
  packages/logger-prettify/package.json
  packages/logger/package.json
  packages/plugins/local-storage/src/fs.ts
  packages/utils/package.json
  packages/verdaccio/src/server/registry.ts
Labels: topic: maintenance

#3576 Fix build target 5x
  .changeset/fluffy-papayas-lay.md
  packages/config/.babelrc
  packages/core/core/.babelrc
  packages/core/tarball/.babelrc
  packages/core/url/.babelrc
  packages/utils/.babelrc
Labels: 5.x branch, topic: maintenance

#3579 fix: update docker base to 18.13.0
  Dockerfile
Labels: Docker, 5.x branch

#3580 feat: expose middleware utils
  .changeset/big-years-repair.md
  .github/workflows/e2e-ci.yml
  packages/api/src/index.ts
  packages/middleware/.babelrc
  packages/middleware/jest.config.js
  packages/middleware/package.json
  packages/middleware/src/index.ts
  packages/middleware/src/middleware.ts
  packages/middleware/src/middlewares/allow.ts
  packages/middleware/src/middlewares/antiLoop.ts
  packages/middleware/src/middlewares/encode-pkg.ts
  packages/middleware/src/middlewares/error.ts
  packages/middleware/src/middlewares/final.ts
  packages/middleware/src/middlewares/json.ts
  packages/middleware/src/middlewares/log.ts
  packages/middleware/src/middlewares/match.ts
  packages/middleware/src/middlewares/media.ts
  packages/middleware/src/middlewares/security-headers.ts
  packages/middleware/src/middlewares/validation.ts
  packages/middleware/src/types.ts
  packages/middleware/test/allow.spec.ts
  packages/middleware/test/encode.spec.ts
  packages/middleware/test/final.spec.ts
  packages/middleware/test/helper.ts
  packages/middleware/test/json.spec.ts
  packages/middleware/test/log.spec.ts
  packages/middleware/test/loop.spec.ts
  packages/middleware/test/media.spec.ts
  packages/middleware/test/params.spec.ts
  packages/middleware/test/security.spec.ts
  packages/utils/src/index.ts
  packages/utils/src/middleware-utils.ts
  packages/utils/test/middleware-utils.spec.ts
  packages/web/src/middleware/web-api.ts
  pnpm-lock.yaml
Labels: dev: refactor, topic: maintenance
