Repository verdaccio/verdaccio, pull requests merged in 2023-10, with the labels that each got.

#4051 fix: display labels for engine versions
  .changeset/eight-squids-judge.md
  packages/plugins/ui-theme/src/i18n/crowdin/ui.json
  packages/ui-components/src/components/Engines/Engines.tsx
Labels: topic: ui

#4057 fix: Avoid 404 error when getting favicon on root
  .changeset/weak-fans-explain.md
  packages/server/express/src/server.ts
Labels: bug: fixed, topic: web

#3914 feat(experiment): accept async tarball_url_redirect function
  src/api/endpoint/api/package.ts
  test/helpers/initializeServer.ts
  test/unit/modules/api/_helper.ts
  test/unit/modules/api/config/experiments.yaml
  test/unit/modules/api/experiments.spec.ts
  test/unit/modules/api/legacy/api.__c.ts
Labels: 6.x branch

#4071 feat: ui improvements
  .changeset/long-jars-collect.md
  packages/core/types/src/configuration.ts
  packages/middleware/src/middlewares/web/utils/renderHTML.ts
  packages/plugins/ui-theme/package.json
  packages/plugins/ui-theme/src/i18n/crowdin/ui.json
  packages/plugins/ui-theme/tools/_verdaccio.config.yaml
  packages/plugins/ui-theme/tools/webpack.config.js
  packages/ui-components/jest/jest.config.js
  packages/ui-components/package.json
  packages/ui-components/src/components/ActionBar/ActionBar.stories.tsx
  packages/ui-components/src/components/ActionBar/ActionBar.test.tsx
  packages/ui-components/src/components/ActionBar/ActionBar.tsx
  packages/ui-components/src/components/ActionBar/ActionBarAction.tsx
  packages/ui-components/src/components/ActionBar/__snapshots__/ActionBar.test.tsx.snap
  packages/ui-components/src/components/Author/Author.tsx
  packages/ui-components/src/components/Author/__snapshots__/Author.test.tsx.snap
  packages/ui-components/src/components/Author/styles.ts
  packages/ui-components/src/components/CopyClipboard/CopyToClipBoard.tsx
  packages/ui-components/src/components/Deprecated/Deprecated.tsx
  packages/ui-components/src/components/Engines/Engines.tsx
  packages/ui-components/src/components/Help/__snapshots__/Help.test.tsx.snap
  packages/ui-components/src/components/Install/Install.test.tsx
  packages/ui-components/src/components/Install/Install.tsx
  packages/ui-components/src/components/Install/InstallListItem.tsx
  packages/ui-components/src/components/Package/Package.tsx
  packages/ui-components/src/components/RawViewer/RawViewer.tsx
  packages/ui-components/src/components/Readme/Readme.tsx
  packages/ui-components/src/components/Readme/ReadmeDark.tsx
  packages/ui-components/src/components/Readme/ReadmeLight.tsx
  packages/ui-components/src/components/Readme/__snapshots__/Readme.spec.tsx.snap
  packages/ui-components/src/components/Readme/github-markdown-dark.css
  packages/ui-components/src/components/Readme/github-markdown-light.css
  packages/ui-components/src/components/SettingsMenu/SettingsMenu.tsx
  packages/ui-components/src/components/SideBarTittle/SideBarTittle.tsx
  packages/ui-components/src/components/Versions/HistoryList.tsx
  packages/ui-components/src/components/Versions/Versions.test.tsx
  packages/ui-components/src/components/Versions/Versions.tsx
  packages/ui-components/src/components/Versions/__partials__/data.json
  packages/ui-components/src/components/Versions/__partials__/deprecated-versions.json
  packages/ui-components/src/providers/AppConfigurationProvider/AppConfigurationProvider.tsx
  packages/ui-components/src/providers/PersistenceSettingProvider/PersistenceSettingProvider.tsx
  packages/ui-components/src/store/models/download.ts
  packages/ui-components/src/types/packageMeta.ts
  pnpm-lock.yaml
Labels: topic: ui
