Repository verdaccio/verdaccio, pull requests merged in 2024-03, with the labels that each got.

#4543 fix: newline after version command
  src/lib/cli/commands/version.ts
Labels: 5.x branch

#4545 chore: migrate to @verdaccio/local-storage-legacy
  .pnp.cjs
  .yarn/cache/@verdaccio-local-storage-legacy-npm-11.0.2-4583594381-e5c09028a9.zip
  .yarn/cache/@verdaccio-local-storage-npm-10.3.3-e7afb8358f-70f47ea94f.zip
  package.json
  src/lib/local-storage.ts
  yarn.lock
Labels: dev: refactor, 5.x branch

#4544 feat: enable stream search from user interface
  package.json
  src/api/endpoint/api/v1/search.ts
  src/api/index.ts
  src/api/web/api/index.ts
  src/api/web/api/search.ts
  src/lib/cli/commands/init.ts
  src/lib/search-utils.ts
  src/lib/storage-utils.ts
  src/lib/storage.ts
  src/lib/transform-search-results.ts
  src/lib/versions-utils.ts
  test/unit/modules/web/api.web.spec.ts
  yarn.lock
Labels: topic: search, 6.x branch

#4551 Avoid displaying "prettify pipeline error" if there is no error
  .changeset/slow-wasps-glow.md
  packages/logger/logger-prettify/src/prettify.ts
Labels: core dependencies update

#4552 fix config builder erroring when passed partial config
  .changeset/silent-shirts-knock.md
  packages/config/README.md
  packages/config/src/builder.ts
  packages/config/test/builder.spec.ts
Labels: topic: config

#4555 feat: versions filter by semver range
  .changeset/eighty-lobsters-study.md
  packages/plugins/ui-theme/src/i18n/crowdin/ui.json
  packages/ui-components/.storybook/preview-head.html
  packages/ui-components/jest/jest.config.js
  packages/ui-components/package.json
  packages/ui-components/src/Theme/theme.ts
  packages/ui-components/src/components/Engines/Engines.tsx
  packages/ui-components/src/components/Install/InstallListItem.tsx
  packages/ui-components/src/components/Repository/Repository.tsx
  packages/ui-components/src/components/Versions/HistoryList.tsx
  packages/ui-components/src/components/Versions/Versions.test.tsx
  packages/ui-components/src/components/Versions/Versions.tsx
  packages/ui-components/src/sections/Detail/Tabs.tsx
  packages/ui-components/src/sections/Detail/__snapshots__/Detail.test.tsx.snap
  pnpm-lock.yaml
Labels: topic: feature request, 5.x branch, topic: ui, 6.x branch

#4560 fix: remove search dependency
  .pnp.cjs
  .yarn/cache/@sindresorhus-is-npm-4.6.0-7cad05c55e-83839f13da.zip
  .yarn/cache/@szmarczak-http-timer-npm-4.0.6-6ace00d82d-c29df3bcec.zip
  .yarn/cache/@types-responselike-npm-1.0.0-85dd08af42-e99fc7cc62.zip
  .yarn/cache/@verdaccio-logger-npm-7.0.0-next-7.13-357819a008-da361d661b.zip
  .yarn/cache/@verdaccio-proxy-npm-7.0.0-next-7.13-47a1663d8a-4811981c42.zip
  .yarn/cache/@verdaccio-search-npm-7.0.0-next-7.2-9153f23b22-dfbca86107.zip
  .yarn/cache/cacheable-lookup-npm-6.1.0-3870ff9465-4e37afe897.zip
  .yarn/cache/cacheable-request-npm-7.0.2-e64cc641fc-6152813982.zip
  .yarn/cache/clone-response-npm-1.0.3-f71cb6aff5-4e671cac39.zip
  .yarn/cache/decompress-response-npm-6.0.0-359de2878c-d377cf47e0.zip
  .yarn/cache/defer-to-connect-npm-2.0.1-9005cc8c60-8a9b50d2f2.zip
  .yarn/cache/form-data-encoder-npm-1.7.2-e6028ef027-aeebd87a1c.zip
  .yarn/cache/get-stream-npm-5.2.0-2cfd3b452b-8bc1a23174.zip
  .yarn/cache/got-cjs-npm-12.5.4-32034db3ac-9babdcaaf6.zip
  .yarn/cache/hpagent-npm-1.2.0-0f725aa4fe-b029da695e.zip
  .yarn/cache/http2-wrapper-npm-2.2.1-c033aaabde-e95e55e22c.zip
  .yarn/cache/json-buffer-npm-3.0.1-f8f6d20603-9026b03edc.zip
  .yarn/cache/keyv-npm-4.5.4-4c8e2cf7f7-74a24395b1.zip
  .yarn/cache/lowercase-keys-npm-2.0.0-1876065a32-24d7ebd56c.zip
  .yarn/cache/mimic-response-npm-1.0.1-f6f85dde84-034c78753b.zip
  .yarn/cache/mimic-response-npm-3.1.0-a4a24b4e96-25739fee32.zip
  .yarn/cache/normalize-url-npm-6.1.0-b95bc12ece-4a49446311.zip
  .yarn/cache/p-cancelable-npm-2.1.1-9388305f02-3dba12b4fb.zip
  .yarn/cache/pino-npm-8.17.2-64a1bee46e-fc769d3d7b.zip
  .yarn/cache/process-warning-npm-3.0.0-e1380c08e2-1fc2eb4524.zip
  .yarn/cache/pump-npm-3.0.0-0080bf6a7a-e42e9229fb.zip
  .yarn/cache/quick-lru-npm-5.1.1-e38e0edce3-a516faa255.zip
  .yarn/cache/resolve-alpn-npm-1.2.1-af77edd28b-f558071fcb.zip
  .yarn/cache/responselike-npm-2.0.1-7f64b6e122-b122535466.zip
  package.json
  yarn.lock
Labels: issue: bug
