Repository verdaccio/verdaccio, pull requests merged in 2024-04, with the labels that each got.

#4573 Fix typo in v5 migration guide
  website/blog/2021-04-14-verdaccio-5-migration-guide.md
Labels: docs

#4574 fix: yarn and pnpm logos on homepage
  website/src/components/PackageManagers.tsx
  website/static/img/sponsors/pnpm.svg
  website/static/img/sponsors/yarn.svg
Labels: website

#4576 fix: upgrade docker file base image to v20.12.1
  .github/workflows/smok-test-module.yml
  .npmignore
  Dockerfile
Labels: 5.x branch
