Repository verdaccio/verdaccio, pull requests merged in 2024-12, with the labels that each got.

#4957 fix: error E409 "username is already registered" (adduser)
  .changeset/green-eagles-boil.md
  packages/api/src/user.ts
  packages/auth/src/utils.ts
  packages/auth/test/auth-utils.spec.ts
  packages/auth/test/auth.spec.ts
Labels: feat: auth, bug: fixed

#4976 docs: fix security jwt config example
  website/docs/config.md
  website/versioned_docs/version-6.x/config.md
Labels: docs

#4992 chore: local storage debug messages
  .changeset/thirty-comics-trade.md
  packages/plugins/local-storage/src/local-fs.ts
Labels: topic: logging

#4991 chore(logger): avoid message if level remains the same
  .changeset/clean-beds-wash.md
  packages/logger/logger-commons/src/logger.ts
Labels: topic: logging

#4993 chore(ui): vitest follow-ups
  .changeset/long-singers-drive.md
  packages/plugins/ui-theme/package.json
  packages/plugins/ui-theme/vitest.config.mjs
  packages/plugins/ui-theme/vitest.setup.ts
  packages/ui-components/package.json
  packages/ui-components/vitest.config.mjs
  packages/ui-components/vitest.setup.ts
  pnpm-lock.yaml
Labels: topic: ui, topic: testing

#4990 fix(middleware): allow content-type with charset
  .changeset/fifty-falcons-design.md
  packages/middleware/src/middlewares/media.ts
  packages/middleware/test/media.spec.ts
Labels: topic: middleware

#5000 fix #4984 improved paths for web endpoint
  src/api/web/api/package.ts
Labels: bug: fixed

#5006 fix(api): fix scope handling in package routes
  src/api/web/api/package.ts
Labels: issue: bug

#4972 chore: move tarball utils to core
  .changeset/breezy-geckos-search.md
  packages/core/core/src/index.ts
  packages/core/core/src/pkg-utils.ts
  packages/core/core/src/tarball-utils.ts
  packages/core/core/test/pkg-utils.spec.ts
  packages/core/core/test/tarball-utils.spec.ts
  packages/core/tarball/src/getLocalRegistryTarballUri.ts
  packages/core/tarball/src/index.ts
  packages/core/tarball/tests/getLocalRegistryTarballUri.spec.ts
  packages/middleware/src/middlewares/allow.ts
  packages/store/src/storage.ts
  packages/utils/src/index.ts
  packages/utils/src/middleware-utils.ts
  packages/utils/test/middleware-utils.spec.ts
Labels: dev: refactor, status: investigating

#4977 feat: show version-specific readmes in web ui
  .changeset/strange-pants-chew.md
  packages/web/src/api/readme.ts
  packages/web/test/api.readme.test.ts
  packages/web/test/config/keep-all-readmes.yaml
Labels: topic: web

#5021 chore: website upgrade docusaurus v3 part 1
  packages/tools/translations/package.json
  pnpm-lock.yaml
  website/docs/amazon.md
  website/docs/ansible.md
  website/docs/api/index.md
  website/docs/how-to-deploy-on-AWS.md
  website/docs/notifications.md
  website/docusaurus.config.js
  website/package.json
  website/sidebars.js
  website/versioned_docs/version-6.x/amazon.md
  website/versioned_docs/version-6.x/ansible.md
  website/versioned_docs/version-6.x/api/node-api/index.md
  website/versioned_docs/version-6.x/how-to-deploy-on-AWS.md
  website/versioned_docs/version-6.x/notifications.md
  website/versioned_sidebars/version-6.x-sidebars.json
Labels: website, topic: maintenance
