Repository verdaccio/verdaccio, pull requests merged in 2024-11, with the labels that each got.

#4922 chore: encode parts of URL
  .changeset/rude-birds-design.md
  packages/verdaccio/src/server/request.ts
Labels: security

#4946 chore: fix typedocs warnings
  .changeset/healthy-ducks-drive.md
  packages/config/src/user.ts
  packages/core/types/src/plugins/storage.ts
Labels: docs

#4945 chore(docs): add links to more articles
  website/docs/articles.md
  website/versioned_docs/version-6.x/articles.md
Labels: docs

#4949 chore(web): fix syntax of test files
  .changeset/cyan-snakes-kiss.md
  packages/web/test/static/runtime.js
  packages/web/test/static/vendor.js
  packages/web/test/static/vendors.js
Labels: topic: web, github_actions

#4948 chore: add info to log when local storage is used
  .changeset/healthy-zoos-lie.md
  packages/store/src/local-storage.ts
Labels: topic: logging

#4944 chore(deps): update version comments in actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-publish.yml
  .github/workflows/shared-docker-publish.yml
Labels: dependencies, github_actions

#4942 chore: move agent_options to config
  .changeset/clever-bees-happen.md
  packages/core/types/src/configuration.ts
  packages/proxy/src/agent.ts
  packages/proxy/src/proxy.ts
Labels: topic: config

#4943 chore: add `error` to log level enum
  .changeset/early-eyes-float.md
  packages/core/types/src/configuration.ts
Labels: topic: logging, topic: config

#4955 fix: readme prettier
  README.md
Labels: topic: readme

#4959 chore: avoid vitest warning
  vitest.config.mjs
Labels: dev: tooling

#4956 chore: add info to log when audit, htpasswd, theme are used
  .changeset/gold-squids-watch.md
  packages/auth/src/auth.ts
  packages/server/express/src/server.ts
  packages/store/src/local-storage.ts
  packages/web/src/middleware.ts
Labels: topic: logging

#4935 chore: version details and history
  README.md
  SECURITY.md
  VERSIONS.md
Labels: dev: do-not-merge, docs

#4965 chore: reuse workflows configurations
  .github/actions/build-app/action.yml
  .github/actions/cache-packages/action.yml
  .github/actions/cache-store/action.yml
  .github/actions/install-app-node/action.yml
  .github/actions/install-app/action.yml
  .github/workflows/ci.yml
  .github/workflows/e2e-ci.yml
  .github/workflows/e2e-ui.yml
  .github/workflows/plugin-generator-e2e.yaml
  .github/workflows/static-data.yml
  .github/workflows/ui-components.yml
  .github/workflows/website.yml
  e2e/ui/package.json
Labels: dev: ci-build, topic: maintenance

#4966 chore: tweak error logging messages
  .changeset/tricky-impalas-shake.md
  packages/plugins/local-storage/src/local-fs.ts
  packages/store/src/storage.ts
Labels: topic: logging

#4961 feat: keep_readmes option when publishing packages
  .changeset/rude-socks-walk.md
  packages/core/types/src/configuration.ts
  packages/store/src/lib/storage-utils.ts
  packages/store/src/storage.ts
  packages/store/test/storage-utils.spec.ts
  packages/store/test/storage.spec.ts
Labels: cmd: publish, topic: readme

#4971 chore(core): typing, naming, and docs of parameters
  .changeset/curvy-rockets-camp.md
  packages/core/core/src/plugin-utils.ts
Labels: dev: refactor

#4969 chore(api): fix void return for some tests
  .changeset/stupid-camels-build.md
  packages/api/test/integration/package.spec.ts
  packages/api/test/integration/publish.spec.ts
  packages/api/test/integration/star.spec.ts
Labels: topic: testing

#4970 chore(loader): fix types for plugin options
  .changeset/cool-seals-watch.md
  packages/config/src/config.ts
  packages/loaders/src/plugin-async-loader.ts
  packages/loaders/test/partials/config/valid-plugin-store.yaml
  packages/loaders/test/partials/test-plugin-storage/verdaccio-plugin-store/index.js
  packages/loaders/test/partials/test-plugin-storage/verdaccio-plugin-store/package.json
  packages/loaders/test/plugin_loader_async.spec.ts
Labels: plugins, topic: config
