Repository verdaccio/verdaccio, pull requests merged in 2025-06, with the labels that each got.

#5202 feat: web v1 login frontend (experimental)
  .changeset/clean-rings-listen.md
  .changeset/poor-hats-smile.md
  packages/api/src/index.ts
  packages/api/src/v1/login.ts
  packages/api/test/integration/config/login.yaml
  packages/api/test/integration/login.spec.ts
  packages/config/src/config.ts
  packages/core/core/src/constants.ts
  packages/core/core/src/error-utils.ts
  packages/core/i18n/src/crowdin/ui.json
  packages/core/types/src/configuration.ts
  packages/middleware/src/middlewares/api_urls.ts
  packages/middleware/src/middlewares/web/render-web.ts
  packages/middleware/src/middlewares/web/web-urls.ts
  packages/plugins/ui-theme/src/App/App.tsx
  packages/plugins/ui-theme/src/App/AppRoute.tsx
  packages/plugins/ui-theme/src/pages/Security/AddUser.tsx
  packages/plugins/ui-theme/src/pages/Security/ChangePassword.tsx
  packages/plugins/ui-theme/src/pages/Security/Login.tsx
  packages/plugins/ui-theme/src/pages/Security/Success.tsx
  packages/plugins/ui-theme/src/pages/Security/index.ts
  packages/ui-components/.npmignore
  packages/ui-components/src/AppTest/AppRoute.tsx
  packages/ui-components/src/AppTest/pages/Security/AddUser.tsx
  packages/ui-components/src/AppTest/pages/Security/ChangePassword.tsx
  packages/ui-components/src/AppTest/pages/Security/Login.tsx
  packages/ui-components/src/AppTest/pages/Security/Success.tsx
  packages/ui-components/src/AppTest/pages/Security/index.ts
  packages/ui-components/src/components/LoginDialog/LoginDialog.tsx
  packages/ui-components/src/index.ts
  packages/ui-components/src/layouts/Security/Dialog.tsx
  packages/ui-components/src/sections/Header/Header.tsx
  packages/ui-components/src/sections/Security/AddUser.tsx
  packages/ui-components/src/sections/Security/ChangePassword.tsx
  packages/ui-components/src/sections/Security/Login.tsx
  packages/ui-components/src/sections/Security/LoginError.tsx
  packages/ui-components/src/sections/Security/Success.tsx
  packages/ui-components/src/sections/Security/index.ts
  packages/ui-components/src/sections/Security/styles.ts
  packages/ui-components/src/sections/Security/utils.ts
  packages/ui-components/src/store/index.ts
  packages/ui-components/src/store/models/add-user.ts
  packages/ui-components/src/store/models/change-password.ts
  packages/ui-components/src/store/models/index.ts
  packages/ui-components/src/store/models/login-v1.ts
  packages/ui-components/src/store/models/utils.ts
  packages/ui-components/src/utils/routes.ts
Labels: feat: auth, status: reviewing proposal, topic: ui

#5275 fix: unpublish broken #5214
  src/api/endpoint/api/publish.ts
Labels: 6.x branch (latest)

#5250 fix: anonymous access web ui (6.x)
  src/api/web/api/package.ts
  test/unit/partials/config/yaml/api.web.spec.yaml
Labels: topic: ui, 6.x branch (latest)

#5280 fix: config web login default
  .changeset/real-balloons-travel.md
  packages/web/src/api/package.ts
  packages/web/test/config/web.yaml
Labels: topic: web

#5279 fix: config web login default (6.x)
  src/api/web/api/package.ts
  test/unit/partials/config/yaml/api.web.spec.yaml
Labels: topic: web, 6.x branch (latest)

#5307 chore(api): remove obsolete tests
  .changeset/violet-poems-walk.md
  packages/api/test/unit/publish.disabled.ts
Labels: topic: testing

#5304 fix: allow config changes in docker image (6.x)
  Dockerfile
Labels: Docker

#5298 chore(deps): signature, utils
  .changeset/few-poets-bathe.md
  packages/signature/package.json
  packages/signature/src/legacy-signature/index.ts
  packages/signature/src/signature.ts
  packages/utils/package.json
  packages/utils/src/crypto-utils.ts
  pnpm-lock.yaml
Labels: dependencies

#5295 chore(deps): local-storage
  .changeset/friendly-feet-sing.md
  packages/plugins/local-storage/package.json
  packages/plugins/local-storage/src/dir-utils.ts
  packages/plugins/local-storage/src/fs.ts
  packages/plugins/local-storage/src/local-database.ts
  packages/plugins/local-storage/src/local-fs.ts
  packages/plugins/local-storage/src/utils.ts
  packages/plugins/local-storage/tests/dir-utils.test.ts
  packages/plugins/local-storage/tests/local-database.test.ts
  packages/plugins/local-storage/tests/local-fs.test.ts
  packages/plugins/local-storage/tests/token.test.ts
  packages/plugins/local-storage/tests/utils.test.ts
  pnpm-lock.yaml
Labels: dependencies

#5288 chore(deps): clean up core modules
  .changeset/seven-peas-obey.md
  packages/core/core/package.json
  packages/core/core/src/file-utils.ts
  packages/core/core/src/plugin-utils.ts
  packages/core/core/src/stream-utils.ts
  packages/core/core/src/tarball-utils.ts
  packages/core/core/src/validation-utils.ts
  packages/core/core/test/mystreams.spec.ts
  packages/core/file-locking/package.json
  packages/core/file-locking/src/legacy/readFile.ts
  packages/core/file-locking/src/legacy/utils.ts
  packages/core/file-locking/src/utils.ts
  packages/core/file-locking/tests/lock.legacy.spec.ts
  packages/core/file-locking/tests/lock.spec.ts
  packages/core/tarball/package.json
  packages/core/tarball/src/getTarballDetails.ts
  packages/core/tarball/tests/getTarballDetails.spec.ts
  packages/core/url/package.json
  packages/core/url/src/index.ts
  pnpm-lock.yaml
Labels: dependencies

#5299 chore(deps): storage
  .changeset/thick-insects-run.md
  packages/store/package.json
  packages/store/src/local-storage.ts
  packages/store/src/storage.ts
  packages/store/test/helpers.ts
  packages/store/test/storage.spec.ts
  packages/store/test/versions.spec.ts
  pnpm-lock.yaml
Labels: dependencies

#5305 fix: allow config changes in docker image
  Dockerfile
Labels: Docker

#5313 chore(deps): built-in node imports
  .changeset/bright-mugs-buy.md
  packages/api/test/integration/_helper.ts
  packages/api/test/integration/publish.spec.ts
  packages/api/test/unit/validate.api.params.middleware.spec.ts
  packages/auth/test/auth-utils-middleware.spec.ts
  packages/auth/test/auth-utils.spec.ts
  packages/auth/test/auth.spec.ts
  packages/auth/test/helper/plugin.ts
  packages/config/src/conf/index.ts
  packages/config/src/config-path.ts
  packages/config/src/config-utils.ts
  packages/config/src/config.ts
  packages/config/src/package-access.ts
  packages/config/src/parse.ts
  packages/config/src/token.ts
  packages/config/src/uplinks.ts
  packages/config/test/config-parsing.spec.ts
  packages/config/test/config-utils.spec.ts
  packages/config/test/config.path.spec.ts
  packages/config/test/config.spec.ts
  packages/config/test/utils/parse-configuration-file.ts
  packages/core/file-locking/src/utils.ts
  packages/hooks/test/__helper/index.ts
  packages/logger/logger-prettify/src/formatter.ts
  packages/middleware/types/custom.d.ts
  packages/node-api/src/server.ts
  packages/plugins/ui-theme/tools/getPackageJson.js
  packages/plugins/ui-theme/tools/webpack.dev.config.babel.js
  packages/proxy/test/proxy.error.___.ts
  packages/server/fastify/debug/index.ts
  packages/store/test/fixtures/test.utils.ts
  packages/store/test/local-store.__disabled__.ts
  packages/tools/docusaurus-plugin-contributors/src/index.ts
  packages/tools/generator-verdaccio-plugin/src/app/index.ts
  packages/tools/generator-verdaccio-plugin/tests/generator-template.test.js
  packages/tools/helpers/src/initializeServer.ts
  packages/tools/local-scripts/src/api/utils.ts
  packages/ui-components/.storybook/main.ts
  packages/verdaccio/src/server/registry.ts
Labels: dependencies

#5316 feat(logger): support redacting sensitive data
  .changeset/cuddly-paws-laugh.md
  packages/config/src/conf/default.yaml
  packages/config/src/conf/docker.yaml
  packages/core/types/src/configuration.ts
  packages/logger/logger-commons/src/logger.ts
  packages/logger/logger-commons/test/logger.spec.ts
  website/docs/logger.md
Labels: topic: logging
